### ISSUE TITLE
Phantom Inferno Spawn

### ISSUE THREAD

**Issue by wheeler9691** [splewis/csgo-retakes#100]
### Expected behavior
Fix broken spawns on new Inferno.

### Actual behavior
There is a phantom spawn in the new Inferno that cannot be teleported to, removed, or avoided it seems.  It is a spawn on the default plant spot in A that spawns you without the bomb resulting in no bomb provided to the T's.

### Steps to reproduce

Load retakes in the new Inferno, edit spawns, remove all T spawns on A.  Leave edit mode.  There will be a spawn on A site, at default, where as the only T player, you do not receive a bomb.

- Plugin version: 0.3.2
- Sourcemod version: 1.8.0.5992

**Comment by splewis** [comment]
You're mixing several things together. It sounds like you're describing a bug with the plugin's edit mode not deleting spawns, but you also mention inferno specifically. Can you clarify? How are you removing the spawns? 

I know the spawns packaged into the release are out of date (https://github.com/splewis/csgo-retakes/issues/90), but I can't tell if you're describing a plugin bug or just saying there's a spawn inside a box you don't know how to delete.

**Comment by wheeler9691** [comment]
Hey, sorry for the confusion.  I was trying to meet the issue template and it's a little harder to articulate than that.

So I knew when I installed the plugin that the Inferno spawns had problems with being stuck in walls.  I went through and fixed all of those spawns by visibly seeing them or by using "4. Teleport to nearest spawn" for spawns that were not visible.  

Those are all good, however, there is a T spawn on A site that I cannot remove.  It is at default.  I can remove all T spawns on A site, by teleporting and deleting until I'm teleported to a CT spawn.  I then stand at default and press 4 to teleport to the nearest spawn and I'm teleported all the way to CT.  ie. "The nearest spawn".  This leads me to believe the plugin or spawn config doesn't know this spawn is there.

So I'm in my server trying to get it populated, but 50% of the A-site rounds spawn me at default with no bomb by myself.  Let me know if I can explain anything a little better.  Thanks for your help.

**Comment by wheeler9691** [comment]
I've found more...  Still Inferno is the only map with this problem.  

One is in CT spawn in the wall.  This is a spawn for B site.

Another is a T spawn at A site.  It is halfway between truck and porch.  I also cannot teleport to this one either.

Am I running the wrong gametype/gamemode?  I'm using casual, should it be competitive?  I noclip through walls to try to see these spawns and they aren't there.  Please help.

**Comment by splewis** [comment]
You could just delete the exist spawn file and recreate them. It's at addons/sourcemod/configs/retakes/de_inferno.cfg.

**Comment by wheeler9691** [comment]
I'll give that a shot, thank you.

**Comment by wheeler9691** [comment]
Ok, so I got some new server parts and started building on my endgame server.  I've rebuilt the server from scratch on Ubuntu Server 17.04.

I went ahead and deleted all the spawns from addons/sourcemod/configs/retakes/de_inferno.cfg as advised.  I then proceeded to enter the game, verify that no spawns were present, and started adding spawns.  I haven't gotten enough people in my server to verify that there are no bad spawns, but I'm having a strange issue with the bomb.

On Inferno, I have 2 spawns on A site for T's.  These are both "normal" spawns, but only one of them is given the bomb.  [Here are the two spawns.](http://i.imgur.com/PBbzPNV.jpg)  If I spawn on the right in the corner, I'm given the bomb, no problem.  If I spawn on the left I am not given the bomb.  Now, I am playing alone, so I don't know if that makes a difference.

I have the same problem on B site for T's.  [Here is the B site spawns](http://i.imgur.com/7XH5RAW.jpg).  Just like on A, if I spawn on the bottom right spawn I get the bomb no problem.  If I spawn on the left I do not get the bomb.

I don't know if this problem will disappear by having more than one player, but I'd prefer to figure it out before going live.  And I'm ready to clone 3 more virtual machines for these servers, but I'm stuck.

**Comment by wheeler9691** [comment]
Ok, so I'm trying to narrow this problem down.  I removed all the spawns from A and B site.  The only spawns are normal spawns outside the plant zone.

Then I would spawn on the normal spawns with the bomb and have to run onto the site.  This made sense to me.

So I decided to add a single spawn to both A and B site that was "Only bomb carrier".  After adding these spawns, I exclusively spawn there and without the bomb.

This is getting very frustrating and your help would be appreciated.

Could it be because I'm playing alone?
Could it be because I'm using Casual mode?  Gametype 0 Gamemode 0?

Your help is greatly appreciated.  If you find me a solution I'll paypal you $10 or something.  I'm getting desperate.

**Comment by splewis** [comment]
The settings are fine.

Can you post the spawns config file you're using?

**Comment by wheeler9691** [comment]
`"Spawns"
{
	"0"
	{
		"origin"		"2339.039062 1656.886108 160.031250"
		"angle"		"11.167274 89.069427 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"1"
	{
		"origin"		"1829.661377 1553.867310 160.031250"
		"angle"		"63.558086 95.944939 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"2"
	{
		"origin"		"1639.390625 1960.263550 160.031250"
		"angle"		"7.385525 89.500404 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"3"
	{
		"origin"		"1652.284180 2089.957764 160.031250"
		"angle"		"11.979074 88.921104 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"4"
	{
		"origin"		"247.011993 543.676941 81.143875"
		"angle"		"7.326097 120.515358 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"5"
	{
		"origin"		"-129.264389 809.506653 33.644035"
		"angle"		"-4.771706 30.836206 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"6"
	{
		"origin"		"196.514008 447.771912 68.854042"
		"angle"		"0.534649 6.779212 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"7"
	{
		"origin"		"86.364304 848.045349 73.596954"
		"angle"		"-0.296958 -59.956810 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"8"
	{
		"origin"		"-100.152710 -115.025162 31.366158"
		"angle"		"-2.177935 1.626050 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"9"
	{
		"origin"		"1645.482178 2168.998291 160.031250"
		"angle"		"10.989013 -89.686584 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"10"
	{
		"origin"		"2367.731445 2535.317383 128.031250"
		"angle"		"5.959847 -90.028122 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"11"
	{
		"origin"		"2414.614746 2129.383057 128.031250"
		"angle"		"3.702619 -100.541344 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"12"
	{
		"origin"		"1735.211792 -90.851463 130.568771"
		"angle"		"7.128122 138.862228 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"13"
	{
		"origin"		"2080.943604 -311.875824 256.031311"
		"angle"		"23.780020 90.881882 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"14"
	{
		"origin"		"2107.232910 -284.083252 85.031250"
		"angle"		"8.534051 90.896706 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"15"
	{
		"origin"		"2537.782471 -138.973663 84.031250"
		"angle"		"2.455462 172.898346 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"16"
	{
		"origin"		"2487.968750 213.093277 127.424965"
		"angle"		"0.633857 -171.271606 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"17"
	{
		"origin"		"4.011211 2519.714600 160.031250"
		"angle"		"2.158240 9.695050 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"18"
	{
		"origin"		"29.945301 3126.409912 160.031250"
		"angle"		"1.960248 -41.418823 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"19"
	{
		"origin"		"449.019714 3281.977783 160.031250"
		"angle"		"1.742461 -90.320000 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"20"
	{
		"origin"		"1821.000610 276.031250 160.031250"
		"angle"		"58.885326 -86.717094 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"1"
	}
	"21"
	{
		"origin"		"557.251465 2900.899902 160.031250"
		"angle"		"65.063148 32.008942 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"1"
	}
}
`

**Comment by wheeler9691** [comment]
As you can see, I have all normal spawns, all outside the plant zones, except, the last two spawns are both bomb carrier only and inside the plant zone, but I'm spawned there without the bomb repeatedly.

**Comment by splewis** [comment]
Spawn id 20 is too close to the wall and for some reason that prevents the player from being given the bomb. 

Moving it to

```
"20"
{
"origin"	"1921.000610 320.031250 160.031250"
"angle"	"58.885326 -86.717094 0.000000"
"bombsite"	"A"
"team"	"T"
"type"	"1"
}
```

fixed the problem.

**Comment by wheeler9691** [comment]
Thanks for this, I'll give it a shot.
