### ISSUE TITLE
5/24/2017 Update Crash

### ISSUE THREAD

**Issue by dracsovd** [splewis/csgo-retakes#101]
The latest CSGO Update is causing my Retake Servers to crash.

"CS:GO Retakes" (0.3.3-dev+126) by splewis

 SourceMod Version Information:
    SourceMod Version: 1.8.0.5995
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5995)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: May 13 2017 09:26:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/d8e6ddc
    Build ID: 5995:d8e6ddc
    http://www.sourcemod.net/

Metamod:Source version 1.10.7-dev
Built from: https://github.com/alliedmodders/metamod-source/commit/4403e81
Build ID: 957:4403e81
Loaded As: Valve Server Plugin
Compiled on: Apr 26 2017
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

**Comment by inot** [comment]
Same problem

**Comment by dracsovd** [comment]
Apparently sourcemod itself has to update gamedata.

Apologies for this.

**Comment by spacecow123** [comment]
Can you explain how you fixed the error @dracsovd ?  Thanks!

**Comment by inot** [comment]
@spacecow123 Update sourcemod + metamod and everything fine.

**Comment by splewis** [comment]
https://forums.alliedmods.net/showthread.php?t=297788
