### ISSUE TITLE
No retakes.cfg in csgo/cfg/sourcemod/ 

### ISSUE THREAD

**Issue by LUK3HUNT** [splewis/csgo-retakes#106]
No retakes.cfg in csgo/cfg/sourcemod/  
I can't join to T side.

**Comment by splewis** [comment]
The retakes.cfg file is autogenerated by the plugin when it first loads. If it's not, check the error logs (addons/sourcemod/logs) and verify retakes.smx is actually in addons/sourcemod/plugins.

**Comment by splewis** [comment]
Closing since there's been no update.

Feel free to reopen if you have problems still.
