### ISSUE TITLE
More fair changing to T side

### ISSUE THREAD

**Issue by gorgitko** [splewis/csgo-retakes#107]
Hello,

is it possible to implement more fair changing to T side? I mean for each round there will be some inner scoreboard of CT players and for each of kill, assist, defuse will players get points, e.g. kill - 3 points, assist 2 points, defuse 1 point. Top N players will be then chosen to switch to T side. Now assists aren't counted at all and sometimes it just sucks.

Thanks!

**Comment by splewis** [comment]
The plugin tracks an internal scoring mechanism (see https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes.sp#L537) and pulls players out of a priority queue based on that score each round. You can see the current score weighting in the code, but it's 50 points for a kill, and 1 point per point of damage. (so a 100 dmg kill is 150 points, 60 dmg is 60 points)

I don't really see much use in changing it. There's a [Retakes_OnPreRoundEnqueue](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L41) you can use to implement your own scoring mechanism.

**Comment by gorgitko** [comment]
Well, I didn't know about this mechanism! I am sometimes pissed off when I have some assists, but didn't move to T side. It seems these assists are really bad in sense of damage :) Current mechanism is even more fair than what I suggested. So no need for change!
