### ISSUE TITLE
How do I pause this pattern in the game?

### ISSUE THREAD

**Issue by wyfang** [splewis/csgo-retakes#108]
There is no way in the game when the switch will be the normal game? Or tell me how to temporarily remove this model approach.

**Comment by splewis** [comment]
I really don't understand your question.

Maybe you're referring to setting the sm_retakes_auto_set_teams cvar to 0? That turns off team swapping, but has some bugs (see #102).

**Comment by wyfang** [comment]
I mean, how should I temporarily remove this plugin, that is, the plugin does not work. I want to restore the normal server. I'm sorry for my English. Also, you are google team!

**Comment by splewis** [comment]
You set sm_retakes_enabled 0 or remove the plugin.
