### ISSUE TITLE
Server crashes on player join

### ISSUE THREAD

**Issue by gorgitko** [splewis/csgo-retakes#109]
Retakes plugin is not working with latest SM (6017) and MM (959) on Linux server. Server crashes immediately when player joins the game. When I disable Retakes plugins (retakes.smx, retakes_standardallocator.smx), server is working normally. I have tried server validation, but crashes still persist.

- Plugin version: 0.3.2
- Sourcemod version: 6017
- Metamod version: 959

No errors in SM log. Server console:

```
Segmentation fault
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Fri Aug 18 12:24:44 CEST 2017: Server restart in 10 seconds
LD_LIBRARY_PATH=/home/csgo-retakes2/serverfiles/bin:/home/csgo-retakes2/serverfiles:/home/csgo-retakes2/serverfiles/bin:
#
#Console initialized.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
```

AlliedMods post: https://forums.alliedmods.net/showthread.php?p=2542363#post2542363

**Comment by nicedayzhu** [comment]
same problem for my win server

**Comment by romkazor** [comment]
same problem
Listing 5 plugins:
  [01] SourceMod (1.8.0.6017) by AlliedModders LLC
  [02] CS Tools (1.8.0.6017) by AlliedModders LLC
  [03] SDK Tools (1.8.0.6017) by AlliedModders LLC
  [04] SDK Hooks (1.8.0.6017) by AlliedModders LLC
  [05] DHooks (2.0.1) by AlliedModders

**Comment by gorgitko** [comment]
Maybe related to latest CSGO update? http://blog.counter-strike.net/index.php/2017/08/19239/

**Comment by romkazor** [comment]
its not retake mod problem, its global problem with sourcemod, may closed
https://forums.alliedmods.net/showthread.php?t=300464

**Comment by gorgitko** [comment]
@romkazor But as I said, when retakes plugins are disabled, server runs fine.

**Comment by Technoblazed** [comment]
Do you have any error logs in your /addons/sourcemod/logs/ directory?

**Comment by Technoblazed** [comment]
Update:  Restart your server twice, update your gamedata, I can't replicate these issues anymore.

**Comment by gorgitko** [comment]
Yeah, latest SM (6020) brings updated gamedata. Will try asap.

**Comment by Technoblazed** [comment]
You don't need to reupload sourcemod to update gamedata

**Comment by gorgitko** [comment]
But I have a nice tool (SM updater) which do it on all servers at once :)

**Comment by Technoblazed** [comment]
Just restart your servers twice lol

**Comment by gorgitko** [comment]
Huh, did I miss something? Gamedata is a part of SM and it is not updated automatically on server restart, is it?

**Comment by splewis** [comment]
https://wiki.alliedmods.net/Gamedata_Updating_(SourceMod)
