### ISSUE TITLE
No chat message on first round

### ISSUE THREAD

**Issue by BrutalCSkakan** [splewis/csgo-retakes#11]
So, the chatmessage saying what bombsite the retake should be on didn't show up on the first round after the warmup. Haven't checked if it's a common issue or something that happens sometimes yet.

**Comment by BrutalCSEjziponken** [comment]
Maybe you should check that then before reporting it. Lets not make splewis both check and fix it. :P

**Comment by splewis** [comment]
Closing since I don't believe there is a bug here.
