### ISSUE TITLE
Pugsetup pluggin and retakes!

### ISSUE THREAD

**Issue by Hypixc** [splewis/csgo-retakes#110]
Hello, i have a server running pugsetup pluggin, and wondered that it would be cool and useful to be able to have retake in the same server... is that possible somehow?
- and if, how should i set it up?

**Comment by splewis** [comment]
I don't know what you want, so I can't help you set it up.

Both plugins have a bunch of config options you can read though:
https://github.com/splewis/csgo-pug-setup/blob/master/README.md#convars
https://github.com/splewis/csgo-retakes/blob/master/README.md#configuration

You could set sm_retakes_enabled 0 in your pugsetup live/warmup configs and then set it to 1 in a sm_pugsetup_postgame_cfg config. That's probably the easiest way.

**Comment by splewis** [comment]
Closing since there's been no response.
