### ISSUE TITLE
Adding in Zeus to the setup?

### ISSUE THREAD

**Issue by ownage13** [splewis/csgo-retakes#111]
So I was wondering as I run 18 servers with your retake setup how hard it would be to add zeus to the gun menu or start with zues in the setup? I have quite a few players who have suggested it and I have gone through the .sp file myself but it looks like it would be rather complicated (and more than i can handle myself) getting a zeus into the setup and why I have come here and asked you to see how hard it would be. 

Anyways besides that I think this plugin runs flawlessly. Thank you for all the time and effort you have spent working on this plugin (:

**Comment by splewis** [comment]
Not hard. I'm not going to add it though. You'd write your own 'weapon allocator' plugin or based it off the [included one](https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_standardallocator.sp).

If you need help or want someone to do it for you, the [sourcemod forums](https://forums.alliedmods.net/index.php) are a good place to ask.

**Comment by ownage13** [comment]
Thanks for the help. I'll see what i can do and ask for help there then. Thanks for your time
