### ISSUE TITLE
gun allocation

### ISSUE THREAD

**Issue by abhit17** [splewis/csgo-retakes#112]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
some force rounds should be added if terrorist are winning continue and then if they win force round then piston for r 

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by splewis** [comment]
I'm not planning on adding anything like this to the retakes plugin. It has an [api](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L107) meant for other developers to define how weapons are given out.
