### ISSUE TITLE
Adding allocation

### ISSUE THREAD

**Issue by abhit17** [splewis/csgo-retakes#114]
Can you help about how to edit api for changing how weapons are given out.?
I tried searching the net but cant find anything usefull.

**Comment by splewis** [comment]
There's 2 examples:
https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_standardallocator.sp
https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_pistolallocator.sp]

This is the api:
https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc

If you need further help you should ask on the sourcemod forums: https://forums.alliedmods.net/forumdisplay.php?f=107
