### ISSUE TITLE
Dust2 - new spawns?

### ISSUE THREAD

**Issue by DigitalFriends** [splewis/csgo-retakes#118]
Seems like the old spawns makes players stuck or spawning in walls. 

Will you update the package with new spawns?

**Comment by romkazor** [comment]
Are you blind?! 
https://github.com/splewis/csgo-retakes/commit/5a17f27ddd0b50b0dff7f8d745f5d0b6193081cb

**Comment by DigitalFriends** [comment]
My bad!
