### ISSUE TITLE
Stuck in ground mid doors to a new dust2

### ISSUE THREAD

**Issue by paul8591** [splewis/csgo-retakes#122]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Not stuck in ground

### Actual behavior
Stuck in ground

### Steps to reproduce
- Plugin version: newest
- Sourcemod version: newest

**Comment by romkazor** [comment]
confirm, stuck in mid doors A plant spawn

**Comment by splewis** [comment]
> Plugin version: newest
Sourcemod version: newest

Not useful.

Use newer spawns: https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_dust2.cfg
