### ISSUE TITLE
Dust 2 spawn point near double doors causes players to get stuck

### ISSUE THREAD

**Issue by Aiguos** [splewis/csgo-retakes#123]
### Expected behavior
Spawn near Double Doors in middle

### Actual behavior
Spawn Slightly underground near Double Doors

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by DigitalFriends** [comment]
Yeah, this is still happening for me as well. 

Seems like another update is needed.

**Comment by Technoblazed** [comment]
First of all, for the love of god, please stop using `Latest` as a plugin version, it's honestly the most annoying thing.

I can't replicate this on the latest versions at all, I'm able to walk from both the position in front and behind double doors.

**Comment by Aiguos** [comment]
Sorry about that, new to github @Technoblazed .
I will fix it when i get home.

**Comment by Aiguos** [comment]
@Technoblazed As promised here is a screenshot of the position.
[Imgur](https://imgur.com/a/wcjfI)

**Comment by Technoblazed** [comment]
https://github.com/splewis/csgo-retakes/pull/124

**Comment by splewis** [comment]
Updated: https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_dust2.cfg

This experience strongly makes me not want to ship any configs by default, and make people create their own.
