### ISSUE TITLE
After 30 Rounds Map Change

### ISSUE THREAD

**Issue by imsandeshjagtap** [splewis/csgo-retakes#129]
After 30 Rounds, All Players Vote For Another map (eg. Cobblestone) has 6 votes majority,
Last map gets Repeated again, Automatically.

If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by splewis** [comment]
I don't know if this is a bug report or feature request, but how your server changes maps has nothing to do with this plugin. Sourcemod has map handling [plugins](https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)) and CS:GO has builtin cvars for map votes, neither of which are related to retakes.
