### ISSUE TITLE
BUG Helmet+M4 in Pistolallocator

### ISSUE THREAD

**Issue by die-man** [splewis/csgo-retakes#132]
### Expected behavior
Always mp_free_armor 1, only kevlar and pistols.

### Actual behavior
Sometimes, players receive mp_free_armor 2 + Rifle M4

### Steps to reproduce
- Plugin version: 0.3.2-dev
- Sourcemod version: 1.8.0.6027

**Comment by splewis** [comment]
You probably have another plugin running interfering with things. Otherwise I need full steps to reproduce because nobody else has reported this and I can't reproduce it.
