### ISSUE TITLE
Bombsite message not working.

### ISSUE THREAD

**Issue by RayneDance** [splewis/csgo-retakes#138]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

Expect line in chat displaying which bombsite to retake.

### Actual behavior

No text in chat.

### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.8

Server is retake.cerus.gg no password.  No other plugins installed.  Fresh server with only Meta/SM/Retake mod.

**Comment by splewis** [comment]
You probably didn't install the translations file.

Check addons/sourcemod/logs for any error logs.

**Comment by RayneDance** [comment]
...you're right. My bad. I missed that while setting up at 2 AM lol.
