### ISSUE TITLE
retakes-csgo-my spawns didn't save and how i can load them back?

### ISSUE THREAD

**Issue by Tololo2018** [splewis/csgo-retakes#140]
my spawns didn't save and how i can load them back?

**Comment by splewis** [comment]
You're going to have to explain what your problem is. I don't know what "load them back" means.

You open the editor, add spawns via the !edit menu, and the spawns save on map end.

**Comment by Tololo2018** [comment]
I did it but when I enter to the server the spawns deleted .

**Comment by splewis** [comment]
What version are you using?

Also you should always check addons/sourcemod/logs for any error logs if you run into any sourcemod plugin issues.

**Comment by splewis** [comment]
No update on this. Closing.
