### ISSUE TITLE
How to put CZ75A to the pistol list?

### ISSUE THREAD

**Issue by Nukerz** [splewis/csgo-retakes#141]
how to put weapon_cz75a to the pistol menu?

Tried in retakes_pistolallocator.sp :

#define MENU_TIME_LENGTH 15

char g_PistolChoices[][][] = {
    // Default pistols:
    { "weapon_glock", "Glock" },
    { "weapon_usp_silencer", "USP" },
    { "weapon_hkp2000", "P2000" },

    // Upgraded pistols:
	
    { "weapon_p250", "P250" },
    { "weapon_cz75a", "CZ75-AUTO" }, <<<<<<<*****
    { "weapon_tec9", "Tec-9" },
    { "weapon_fiveseven", "Five-Seven" },
    { "weapon_deagle", "Deagle" },
};

**Comment by splewis** [comment]
That change should work. You probably didn't recompile the plugin - if you need help doing that you should check the sourcemod forums.
