### ISSUE TITLE
How to get more nades?

### ISSUE THREAD

**Issue by przemulas123** [splewis/csgo-retakes#142]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
I just want more nades for everyone

### Actual behavior
U can get one nade or any. :(

### Steps to reproduce
- Plugin version:0.3.4
- Sourcemod version:1.8.0

**Comment by splewis** [comment]
You write another plugin using the api retakes give you: https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L186

Otherwise making the way weapons/nades are given is a long standing feature request: https://github.com/splewis/csgo-retakes/issues/98
