### ISSUE TITLE
wrong spawn without weapons

### ISSUE THREAD

**Issue by Shivam16a** [splewis/csgo-retakes#145]
I am using this plugin on my servers and it is working really good on max 12 player server but recently i found a issue with my max player 20 server. 
Issue is that when server is filled with around 15 or full 20 players then 2 or 3 players from T side are always spawning on T spawn without any guns (with only pistols).

* My retake plugin version is "CS:GO Retakes" (0.3.4+140) by splewis

**Comment by Shivam16a** [comment]
That's the exact error i found
L 05/20/2018 - 01:14:25: [retakes.smx] Failed to get any spawn on de_mirage, site=1, team=2

Does that mean i will have to add more spawn points manually for every map.

**Comment by splewis** [comment]
Yes. The provided spawns (and the gamemode in general) are absolutely not intended to be played by more than 10 people.

**Comment by Shivam16a** [comment]
10 peoples for total or a team.

**Comment by splewis** [comment]
Total.

**Comment by Shivam16a** [comment]
Just one more question consider i create more spawn using sm_edit then exactly which file will get edited so that i can replace the file in other server folders too.

Also thank you so much for assist.
