### ISSUE TITLE
[ Ideas ] Random HP ?

### ISSUE THREAD

**Issue by nguyenbaodanh** [splewis/csgo-retakes#149]
Can add the random HP setting please ?
example 
sm_retakes_hpmin "30"
sm_retakes_hpmax "99"

Players will be set random hp in the range of 30 to 99 hp
This would more fun
Thanks.

**Comment by splewis** [comment]
No. Health can be set by another plugin with the ``Retakes_SetPlayerInfo`` native. 

Something like this would be a useful addition to a customizable weapon/health/etc. plugin as described in https://github.com/splewis/csgo-retakes/issues/98, though (it's also very unlikely that will ever exist).  That said, this will not be added to the base retakes plugin.
