### ISSUE TITLE
chat command to enable/disable mod

### ISSUE THREAD

**Issue by simba93** [splewis/csgo-retakes#150]
I know its possible to use the sm_retakes_enabled command in the console to enable/disable the mod but is there a way to allow my team to use something like !retakes enable/disable in the chat to enable/disable the mod?

Regards

**Comment by splewis** [comment]
You could add entries to the !admin menu, like in https://wiki.alliedmods.net/Custom_Admin_Menu_(SourceMod)#Example_Command

But I don't intend on adding any extra commands for this.
