### ISSUE TITLE
t player model stuck at bombsite a of nuke

### ISSUE THREAD

**Issue by Bearbobs** [splewis/csgo-retakes#151]
player with bomb get stuck at a site nuke

**Comment by b3none** [comment]
If you're still having this issue, hop on the server and use the `!spawns` command. This allows you to go and edit the spawns manually.

**Comment by cryptospook86** [comment]
Fixed the bad spawn point if you want to add it. Ill fix the cbble spawns in a little bit as well. Since the new cbble map jacked em all up on A site.
[de_nuke.txt](https://github.com/splewis/csgo-retakes/files/2559639/de_nuke.txt)
