### ISSUE TITLE
GOTV Bot spawning into games

### ISSUE THREAD

**Issue by mloveless1227** [splewis/csgo-retakes#153]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
GOTV Bot should not spawn into game

### Actual behavior
GOTV Bot is spawning into the game. The Bot does not have a weapon nor does it move, but it is visible and can be killed. The Bot does not show an avatar on the HUD player count nor on the Scoreboard. This started happening when Panorama came out. 

### Steps to reproduce
- Plugin version: Latest (August 1, 2018 commit)
- Sourcemod version: 1.9 git6251
- Steps to reproduce (please be specific): None, happens every round, every map

### ADDITIONAL NOTES

Just to cover what I've done to troubleshoot, I've ensured I'm running the latest stable versions of Sourcemod and Metamod:Source. I have updated to the latest version of the Retakes plugin. There are NO errors being logged in SM. Our configs appear to have no changed and still reflect the default config setup. This immediately started happening after Panorama update. 

Here is a screenshot showing the bot spawned in the middle of Bombsite A on Train: https://imgur.com/a/laE0yze

I'd be glad to provide any further information necessary. Thank you for your time and this plugin

**Comment by splewis** [comment]
> Steps to reproduce (please be specific): None, happens every round, every map

That's not really enough to reproduce; I have retake servers that don't have this issue (with GOTV enabled).

I would try disabling every plugin other than ``retakes.smx`` and seeing if it still happens.

**Comment by splewis** [comment]
No update, and no clear way to reproduce. Feel free to reopen if you can provide more information.

**Comment by RavageCS** [comment]
This is happening on whiffcity servers also.

This has been a bug for a long time(with csgo not the plugin). It has something to do with how you join a team and certain csgo updates seem to make it worse. It's happening on a few other community servers I have joined not running this plugin.

I don't have a server up to be able to test it but from what I remember:
(while in warmup only?)
If you join a team, then switch to spectator, then join team bots spawn.
Certain csgo updates make joining teams glitchy so I assume it's from when people are choosing a team.

If you notice when you are choosing a team after connecting you pick a team but are still at the menu until you press escape.

I think bot_quota cvar is being changed somehow.

It happens on servers with and without gotv enabled.

There was a plugin from allied modders that fixed it from a few years ago, I cant find the link but ill paste the code below. Can't confirm this actually fixes it.

**Comment by RavageCS** [comment]
public Plugin:myinfo =  
{ 
    name = "[CS:GO] Bot Quota fix", 
    author = "Gabe Newell", 
    description = "Bot Quota fix", 
    version = "FINAL", 
    url = "google.com" 
} 

new Handle:g_hBotQuota; 
  
public OnPluginStart() 
{ 
    g_hBotQuota = FindConVar("bot_quota"); 
    if (g_hBotQuota != INVALID_HANDLE) 
    { 
        HookConVarChange(g_hBotQuota, OnBotQuotaChange); 
    } 
} 
  
public OnBotQuotaChange(Handle:cvar, const String:oldVal[], const String:newVal[]) 
{ 
    if (StringToInt(newVal) > 0) 
    { 
        SetConVarInt(cvar, 0); 
        //return Plugin_Handled; 
    } 
}
