### ISSUE TITLE
Spawn in objects

### ISSUE THREAD

**Issue by ReMatchIL** [splewis/csgo-retakes#154]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
just spawn regularly

### Actual behavior
Spawns inside the floor\walls, showing a black screen and a weapon

### Steps to reproduce
- Plugin version:0.3.x
- Sourcemod version: 1.9.0.6241
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Make your own spawns or use ones from https://github.com/splewis/csgo-retakes/tree/master/configs/retakes.

This isn't a bug.

**Comment by ReMatchIL** [comment]
I'm using the spawns from
https://github.com/splewis/csgo-retakes/tree/master/configs/retakes
it does it randomly, and it didn't happen before

‫בתאריך יום ד׳, 22 באוג׳ 2018 ב-5:07 מאת ‪Sean Lewis‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by splewis** [comment]
If you can find a way to reproduce it with 1-2 players, that would be useful. 

Right now you:
1) didn't give a plugin version ("Plugin version:0.3.x")
2) didn't give a spawn file with the issue

I haven't seen any evidence of that there is a issue with the plugin.

**Comment by splewis** [comment]
Closing since there's not enough actionable information here.
