### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by basse27** [splewis/csgo-retakes#155]
hi i was think about making a retake server but i cant get the files to work ore maybe i have placed them not the right place can you maybe send me a guid ore does it nok work whit the new update

regard 
mikael

**Comment by splewis** [comment]
https://github.com/splewis/csgo-retakes#installation

Note the part that says:

> From the download, you should have installed the following (to the csgo directory):
addons/sourcemod/plugins/retakes.smx
addons/sourcemod/translations
cfg/sourcemod/retakes

Check if those are on your server.

**Comment by splewis** [comment]
Closing since there's no update.
