### ISSUE TITLE
8ct v 4t somehow? 

### ISSUE THREAD

**Issue by 3GaNwO** [splewis/csgo-retakes#156]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
5v4 normal retakes

### Actual behavior
8 v 4 had abnormal retakes where there was 8 ct's vs 4 t's 

This is the error logs:

L 08/24/2018 - 07:34:59: SourceMod error session started
L 08/24/2018 - 07:34:59: Info (map "de_nuke") (file "errors_20180824.log")
L 08/24/2018 - 07:34:59: [retakes.smx] Failed to get any spawn on de_nuke, site=0, team=1
L 08/24/2018 - 07:42:57: Error log file session closed.

I have noticed there was someone else who had a similar issue a while back but his fix was an updated game data but for my case I have everything up to date (as far as I know) So I have no idea what could be causing this abnormal behavior.  

### Steps to reproduce
- Plugin version: 0.3.3 
- Sourcemod version: 1.9.0-git6251
- Steps to reproduce (please be specific): having too many players? I'm not quite sure how to replicate this one but changing map and/or restarting the server fixes the issue temporarily.

**Comment by splewis** [comment]
Probably the same issues as described in https://github.com/splewis/csgo-executes/issues/10

I don't know how to fix it.

**Comment by 3GaNwO** [comment]
Okay so with the new CSGO update im getting errors in my logs that show that spawns aren't being properly allocated which is now causing my servers to fill entirely and get 5v5, 6v5, 7v4, 8v4 and somehow 8v5 (which is odd cause i run 12 slot servers). My admins happen to notice it when only VIP's have been there to fill the server has it gone to weird rounds. 

I should note that I'm on Sourcemod 1.9 build 6267 and that I have already gone ahead and updated to your most recent update. 

Error in logs (really only error in my logs just has it on different maps) 

"L 11/11/2018 - 20:19:21: [retakes.smx] Failed to get any spawn on de_nuke, site=1, team=1"

And when I check on the console tool on NFO and use sm plugins list I see no errors in any plugins 

What should I do to try and get this functioning properly again. I put this comment here cause I thought maybe it could be the same issue just now its finally showing a lot errors in my logs
