### ISSUE TITLE
Server crashing with Retakes.smx 

### ISSUE THREAD

**Issue by mloveless1227** [splewis/csgo-retakes#159]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Server operates as normal

### Actual behavior
Server is crashing when retakes.smx is attempts to load on Linux servers after last nights update. Tested on multiple Linux servers on different machines. Have not tested on Windows. Others on Allied Mods are also claiming Retakes,  1v1 arena, and a couple other plugins are causing server crashes since last night's CS:GO update.

### Steps to reproduce
- Plugin version: latest
- Sourcemod version: 1.9.0-git6252
- Steps to reproduce (please be specific): There are no steps. Server crashes with retakes.smx, as soon as it's removed, server starts.

**Comment by mohitkyadav** [comment]
Please resolve this soon, thanks.

**Comment by DigitalFriends** [comment]
Having the same issue here, however it works just fine on 1/12 servers (latest stable mm/sm, 12 forks of the same gameserver)

**Comment by ipsingh06** [comment]
I can confirm that the latest dev build of Sourcemod v1.10.6339 fixes the crash.

**Comment by tk1114632** [comment]
> I can confirm that the latest dev build of Sourcemod v1.10.6339 fixes the crash.

Not fixed my issue.

**Comment by splewis** [comment]
This isn't a plugin issue. It's a sourcemod issue.

alliedmodders/sourcemod#893 looked to fix it. If you have crashes, get a newer soucemod build from 1.9 or 1.10. 1.10 is unstable, so I suggest sticking to 1.9.

**Comment by kunalpowar** [comment]
I can confirm that build 6254 under branch 1.9 works.

**Comment by usparker** [comment]
Hey fellas, I am still running into issues after downloading the latest retakes-sourcemod, ive clean reinstalled my server on gameservers probably 5 times and now our server is not even online lol (RIP) my knowledge of running servers is not extremely well, but its decent and it seems since the big csgo update 15 days ago everything I had setup doesnt work. Ideas?
