### ISSUE TITLE
Crashing when second player joins after recent update

### ISSUE THREAD

**Issue by taxon221** [splewis/csgo-retakes#160]
### Expected behavior

Before the recent update on 2018.10.04 my server worked perfectly with this plugin installed correctly

### Actual behavior

After the 2018.10.04 update the server crashes as soon as a second person joins the server they cant even select the team. Reinstalled the server + sourcemod to no fix
Vanilla server works
Sourcemod install works
As soon as you install the retake plugin it crashes when a second player joins

### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.9
- Steps to reproduce (please be specific): Have a second player join the server

**Comment by splewis** [comment]
https://github.com/splewis/csgo-retakes/issues/159
