### ISSUE TITLE
Force to use only bomb defusal maps

### ISSUE THREAD

**Issue by borzaka** [splewis/csgo-retakes#163]
### Expected behavior
Retakes plugin only uses bomb defusal maps (map groups).

### Actual behavior
After map ended, game switched to cs_office :) I voted with the default voting system to `de_mirage`, but `cs_office` was loaded.

`L 10/17/2018 - 02:25:19: [retakes.smx] The retakes config file (addons/sourcemod/configs/retakes/cs_office.cfg) does not exist
`
### Steps to reproduce
- Plugin version: v0.3.4
- Sourcemod version: 1.9.0.6260

Probably the default `nextmap` Sourcemod plugin does this. Disabling it (delete `nextmap.smx`) not resolves the issue.
Edit: well, it was solved by removing `nextmap.smx`..., but !nextmap command remains.

So, what steps should we take to only enable defusal maps with this plugin, and vote with default voting system in the map end? Or disable map change at all at the end? Or auto vote for the next map near to the end of the game?

**Comment by splewis** [comment]
The retakes plugin has nothing to do with how your server selects and changes. Sorry - I can't help with general csgo server configuration.

**Comment by borzaka** [comment]
A note in the readme would do to help others:
Disable `nextmap` Sourcemod default plugin to prevent server switch to a non-defusal map, which - obviously - breaks Retakes plugin.

> If you use CS:GO's built-in map voting and use SourceMod, you **must** disable SourceMod's `nextmap` plugin by moving `addons/sourcemod/plugins/nextmap.smx` to the `addons/sourcemod/plugins/disabled/` folder.
This is because SourceMod will override the server's next map if a plugin tells it to. Which the `nextmap` plugin does on startup.

[source](https://gaming.stackexchange.com/a/251010)
