### ISSUE TITLE
how to allow playing with bots?

### ISSUE THREAD

**Issue by wrjanan** [splewis/csgo-retakes#168]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
When login to game with 1 player, the match will be filled with bots. play continues 4v5, 1 player, 8 ai bots.

### Actual behavior
When login with 1 player, the match filled with bots, but forced to be spectators. Then match goes crazy and keeps restarting round.

### Steps to reproduce
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
Sorry, you can't.
