### ISSUE TITLE
You may only connect to this server from a lobby.

### ISSUE THREAD

**Issue by sickino** [splewis/csgo-retakes#169]
Hey im using 1.8 sourcemod 1.11.0 metamod.. only 3 extra plugins insta defuse, autoplanter, connect message theyre working perfectly i can join server but when i want to use your retakes plugin it wont let me join my server it is saying in console retrying (ip of the server) and after many tries it disconnects me to the lobby and it says You may only connect to this server from a lobby. .. i dont know why does it happen can you help me? i use sv_allow_lobby_connect_only 0

**Comment by splewis** [comment]
It's extremely unlikely this has anything to do with retakes, so I can't really help.

**Comment by sickino** [comment]
i got it.. its working now.. thanks anyways
