### ISSUE TITLE
no guns no bomb in retake after battle royale update

### ISSUE THREAD

**Issue by MeShal606** [splewis/csgo-retakes#173]
hello guys after csgo battle royale update the retake not working the issue is bomb land out site map and after warmap the Weapons Disappear ( no weapons & no bomb )

**Comment by splewis** [comment]
Update sourcemod. If you still have problems after that, post the output of `sm plugins` and `sm exts`.

**Comment by ultramoo** [comment]
had same issue - updating sourcemod fixed it.

**Comment by splewis** [comment]
Closing since there's no update here. A sourcemod update probably fixed it.
