### ISSUE TITLE
Not working, Update Needed, Crashing Server

### ISSUE THREAD

**Issue by MidasKing67** [splewis/csgo-retakes#174]
### Expected behavior
Should have worked normally.

### Actual behavior
Plugin not working
Crashing Server

### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.9.0.6245
- Steps to reproduce (please be specific): Install plugin, start server, join server, when connected plugin not working, after warm up end server crashes.

**Comment by vikas5914** [comment]
@MidasKing67 Please update source mode to the latest version.

**Comment by splewis** [comment]
I don't see any reason retakes needs an update. Update your sourcemod version.
