### ISSUE TITLE
Auto Disconnect in 25 Sec after latest CS GO Update

### ISSUE THREAD

**Issue by W0lfyGER** [splewis/csgo-retakes#176]
Since the Danger Zone Update I got the Problem with my Servers, when I join and the warmup ends I get disconnected from the Server.
Does anyone have the same issue?

**Comment by vikas5914** [comment]
@W0lfyGER Sourcemod version?

**Comment by W0lfyGER** [comment]
> 
> 
> @W0lfyGER Sourcemod version?

Yeah got it. 
Sourcemod Version was 1.8.XYZ 
Updated it to the latest Version now everything runs fine.
But THX mate
