### ISSUE TITLE
Message Dont Show Up at times and this error is thrown into console

### ISSUE THREAD

**Issue by bojank** [splewis/csgo-retakes#18]
L 02/18/2015 - 15:41:24: [SM] Native "PrintToChat" reported: Client 3 is not in game
L 02/18/2015 - 15:41:24: [SM] Displaying call stack trace for plugin "retakes.smx":
L 02/18/2015 - 15:41:24: [SM]   [0]  Line 68, ./scripting/retakes/natives.sp::Native_RetakeMessageToAll()
L 02/18/2015 - 15:41:24: [SM] Native "Retakes_MessageToAll" reported: Error encountered while processing a dynamic native
L 02/18/2015 - 15:41:24: [SM] Displaying call stack trace for plugin "retakes.smx":
L 02/18/2015 - 15:41:24: [SM]   [0]  Line 703, ./scripting/retakes.sp::TerroristsWon()
L 02/18/2015 - 15:41:24: [SM]   [1]  Line 519, ./scripting/retakes.sp::Event_RoundEnd()

**Comment by splewis** [comment]
Should be fixed now. The only occurred when a client was connecting but not fully ingame (i.e. loading the map).
