### ISSUE TITLE
Can't join server when plugin is installed

### ISSUE THREAD

**Issue by AppleML3** [splewis/csgo-retakes#182]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Addon should work

### Actual behavior
Once installed, I can no longer join the server. Once I remove it, I can join the server.

### Steps to reproduce
- Plugin version: Latest
- Sourcemod version: 1.9.0.6245 
- Steps to reproduce (please be specific):

**Comment by YoSoyPhil** [comment]
I am also having this issue, though with sourcemod-1.9.0-git6261 and mmsource-1.10.7-git968-linux.tar.gz.

**Comment by splewis** [comment]
I don't have this issue, and I don't know what "can no longer join the server" means. Does it mean the client crashes? Are there server error (sourcemod error logs)? Does the server crash? There isn't enough information here to really make it worth investigating.

**Comment by AppleML3** [comment]
Well, I forgot I posted this. But I switched server hosts, and that did the trick. My old host was keeping sourcemod out of date constantly.

Old Host: Serenity Servers
New Host: NFOServers

**Comment by YoSoyPhil** [comment]
I think I found out why, sorry for not providing logs Splewis.

I downloaded the master and/or the release - but not the package called containing "retake". So I was missing some files. I did not find any logic to why you release, as you do, but it threw me off quiet a bit tbh.

It is currently working, somewhat atleast on my server now. Only problem being, that sometimes I get into a "0 sec - Round Draw" loop and I can't seem to figure out why. Happens with a vanilla server.cfg. Might just be me missing points again.

Thank you for your contributions!

**Comment by splewis** [comment]
> I downloaded the master and/or the release - but not the package called containing "retake". So I was missing some files. I did not find any logic to why you release, as you do, but it threw me off quiet a bit tbh.

I don't really understand what you mean here at all, but I'm glad you fixed it.

> It is currently working, but always changed to dust2 regardless of votes.

Unrelated to retakes. Sorry, can't help with that.
