### ISSUE TITLE
Need Abbey Spawn

### ISSUE THREAD

**Issue by AkalaGit** [splewis/csgo-retakes#184]
Abbey doesn't have spawns, it needs them.

**Comment by splewis** [comment]
Okay. The spawns in the repo are provided for convenience, it's not a bug that it doesn't include spawns for every single map. The [spawn editor](https://github.com/splewis/csgo-retakes#creating-and-editing-spawns) exists for a reason.

**Comment by AkalaGit** [comment]
I thought you updated the spawns regularly since you (someone else?) added Biome and Subzero spawns in an update. I also tried using the spawn editor before I posted this and got "[Retakes] The editor is currently disabled." even after entering sm_edit into the server console. And after trying that but also before coming here I tried to edit the spawn file manually which is a pain in the ass bc I have to type in the coords manually from cl_showpos 1. Is there a fix for not being able to edit? Do I have to enable spawn editing in a cfg file somewhere?

**Comment by AkalaGit** [comment]
Should I re-enable any of these plugins?
https://gyazo.com/c4634bb44f1bbb055c477bc0d0d8c383

**Comment by splewis** [comment]
> "[Retakes] The editor is currently disabled." even after entering sm_edit into the server console.

Then `sm_retakes_editor_enabled` was disabled on the server. It's enabled by default. You can set it in `cfg/sourcemod/retakes/retakes.cfg`.

**Comment by AkalaGit** [comment]
Yeah that worked. Thanks.
