### ISSUE TITLE
rtv only shows 3 maps

### ISSUE THREAD

**Issue by VNIX17** [splewis/csgo-retakes#186]
The Plugin should give more different map options for rtv or even
normal voting at the end.

It shows only 3 different maps from which you can choose.
But I made more maps ready. 

Plugin version: 0.3.4

Sourcemod version: 1.9.0

Steps to reproduce (please be specific):

Installed the Plugins.
Deleted maps which arent not in the active pool from the maps folder.
Made new Spawn Points.

**Comment by splewis** [comment]
The retakes plugin doesn't manage your map cycle/votes. The retake spawn configs are totally unrelated to that. Setting up mapchooser/map votes is up to you, not retakes.

rtv is a separate plugin. https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)
