### ISSUE TITLE
Priority queue

### ISSUE THREAD

**Issue by nutellazpw** [splewis/csgo-retakes#188]
Is possible to make priority queue for Vip and Admin players on servers?
Need to immediatly join to game and kick random user to spectator.

**Comment by splewis** [comment]
Yes, but it's not something I plan on adding to retakes. 

It's possible to change the queue from another plugin using `Retakes_OnPreRoundEnqueue` and/or `Retakes_OnPostRoundEnqueue` (see https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc).
