### ISSUE TITLE
Feature Request - Enhancement

### ISSUE THREAD

**Issue by 3GaNwO** [splewis/csgo-retakes#190]
Controlled Friendly Fire configs for molly and nades 

I am aware there is the ff_damage_reduction_grenade cvar but even with this enabled (mine set to 0.85 def is 0.25) it doesnt allow the mollies and nades to damage my teammates. Ideally should be a controllable cfg that can enable/disable team damage for nades and mollies

**Comment by splewis** [comment]
Sorry - I think that behavior is much more widely applicable to the game than the retakes gamemode, so it doesn't makes sense to put it inside the retakes plugin, imo.
