### ISSUE TITLE
Not start!

### ISSUE THREAD

**Issue by eniorJR** [splewis/csgo-retakes#199]
hello,, I send this because I have a problem, what happens is that I install the csgserver and add the cfg and addons in the folder, but when the servidior starts, the retake does not work, only a random game comes out.

srry for my english.

**Comment by splewis** [comment]
https://github.com/splewis/csgo-retakes#installation

Did you install metamod:source (typing 'meta version' in console should print the version)? 

Did you install sourcemod? (typing 'sm version' in console should print the version)
