### ISSUE TITLE
Map problems

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-retakes#20]
de_nuke
The bomb has time to go down the vent and plant on B when its A site (12 sec)

de_cbble
CT get stuck on one of the spawns for B site

de_dust2
T can pick some CT off with AWP at their spawnpositions near the normal CT spawn/mid gate

I fixed these problems on my servers but they seem to been overritten? How do I turn off the auto update for spawn files? :S

**Comment by splewis** [comment]
There is no autoupdate for anything involving this plugin.

The spawns are written out every map end (as long as the editor is enabled), though. So you might be experiencing:
- server is on de_dust2
- you update the spawn file (e.g. upload from ftp) the new de_dust2 spawns to the server
- server changes level to de_nuke, which writes out the spawns it previously had
- the spawns are the same as when they started

So you should either:
- disable the editor on "live" servers where you aren't editing the spawns
- only upload spawns when the servers aren't running/you know they aren't on the map you're updating

**Comment by BrutalCSEjziponken** [comment]
thx
