### ISSUE TITLE
server issues

### ISSUE THREAD

**Issue by kilj0y** [splewis/csgo-retakes#200]
Hi im new to having a server for csgo and I loaded your practice mode and it works great. now I would like to load a deathmatch and retakes so I could select what I want to use when me and my friends are playing but I cant load the retakes or deathmatch can you please help me get this working?

**Comment by AG4lyf** [comment]
what you want is a multimod server 
i created some multimod server in past 
and this is how i used to make it work 
i specify the maps to that specific game mode 
for example cache will run retake
mirage will run execute 
by using config per map plugin 
just set sm_retake_enabled ( m not sure about it ) to 0 for the maps u dont want the retake to be played on

**Comment by splewis** [comment]
https://forums.alliedmods.net/forumdisplay.php?f=58 is a much better source for general sourcemod help.
