### ISSUE TITLE
Retake Plugin fucks up !ws by franug

### ISSUE THREAD

**Issue by AshyzBoyz** [splewis/csgo-retakes#202]
### Expected behavior
Player able to !ws and change skin of gun in the midst of a Retake match

### Actual behavior
When player do !ws to change the skin of the weapon he's holding in the middle of a Retake match, the gun he's holding dissapears upon changing the weapon skin. 

### Steps to reproduce
- Plugin version: v0.3.4
- Sourcemod version: build 6281

**Comment by AshyzBoyz** [comment]
Franug's ws plugin works on my pug server. However when i install it with retakes this issue shows up

**Comment by splewis** [comment]
Sorry, I'm not going to take any effort fixing something that only affects a plugin that breaks Valve TOS.
