### ISSUE TITLE
The Map is always dust 2

### ISSUE THREAD

**Issue by ODazzahO** [splewis/csgo-retakes#203]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Automatic rtv changes map at the end of the game to the one the players vote for.

### Actual behavior
Automatic rtv has no effect on the map and its always forced to dust 2 unless manual !rtv in chat before the end of the game, csgos map selector is still active also

### Steps to reproduce
- Plugin version: Latest
- Sourcemod version: Latest

**Comment by ODazzahO** [comment]
![image](https://user-images.githubusercontent.com/51971015/61999518-9b743280-b0ba-11e9-87f0-ac494aebd9b7.png)
Plugins List

**Comment by RavageCS** [comment]
This shouldn't have anything to do with retakes plugin.

Maybe check that you have mp_match_end_changelevel 1

**Comment by AG4lyf** [comment]
Nothing to do with plugin itself , check you're maplist and mapcycle , from csgo folder

**Comment by splewis** [comment]
Sorry, retakes has nothing to do with how your server changes maps.
