### ISSUE TITLE
Fix raspawn de_vertigo

### ISSUE THREAD

**Issue by d0kt0r** [splewis/csgo-retakes#205]
Correct the resp on this map, after the change everyone gets stuck

**Comment by rpkaul** [comment]
"Spawns"
{
	"0"
	{
		"origin"		"-2610.087646 945.030273 11784.144531"
		"angle"		"1.231204 -39.083801 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"1"
	{
		"origin"		"-1680.031250 555.031250 11776.031250"
		"angle"		"0.109487 97.237770 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"2"
	{
		"origin"		"-2603.408203 445.504608 11783.313477"
		"angle"		"10.478882 -58.083935 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"3"
	{
		"origin"		"-1840.470215 1070.073242 11783.776367"
		"angle"		"1.463800 -48.535267 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"4"
	{
		"origin"		"-2151.031250 407.968750 11776.031250"
		"angle"		"7.688158 -122.119347 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"5"
	{
		"origin"		"-679.023499 427.579712 11776.031250"
		"angle"		"1.874177 120.724754 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"6"
	{
		"origin"		"-2383.689697 -1031.039917 11488.031250"
		"angle"		"1.422744 63.928001 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"7"
	{
		"origin"		"-1615.324463 435.858398 11495.683594"
		"angle"		"-4.090271 -147.468048 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"8"
	{
		"origin"		"-1671.991577 -213.278702 11776.031250"
		"angle"		"0.547218 119.535797 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"9"
	{
		"origin"		"-2285.441406 -599.324219 11488.031250"
		"angle"		"-5.444582 53.912395 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"10"
	{
		"origin"		"-88.329231 -1439.969360 11776.031250"
		"angle"		"1.190128 136.459381 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"11"
	{
		"origin"		"-764.543152 -711.968750 11776.031250"
		"angle"		"0.957502 122.738663 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"12"
	{
		"origin"		"-1735.319946 334.359680 11776.031250"
		"angle"		"-2.243562 -21.924984 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"13"
	{
		"origin"		"-1761.256226 913.510254 11776.031250"
		"angle"		"0.738660 -38.832249 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"14"
	{
		"origin"		"-887.638672 765.975037 11776.031250"
		"angle"		"1.162730 -42.909000 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"15"
	{
		"origin"		"-756.550476 452.495880 11776.031250"
		"angle"		"3.666166 -60.926559 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"16"
	{
		"origin"		"-1475.931030 -464.564087 11776.031250"
		"angle"		"-0.930205 118.157272 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"17"
	{
		"origin"		"-910.337524 -136.852127 11776.031250"
		"angle"		"0.082093 104.834137 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"18"
	{
		"origin"		"-1625.502808 -627.495239 11488.031250"
		"angle"		"-1.319727 45.766270 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"19"
	{
		"origin"		"-1557.109009 750.663452 11776.031250"
		"angle"		"1.815283 37.576805 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"20"
	{
		"origin"		"-506.749878 -1450.193481 11776.031250"
		"angle"		"12.216105 112.628571 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"21"
	{
		"origin"		"-708.670044 742.950928 11776.031250"
		"angle"		"0.218819 164.638840 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"22"
	{
		"origin"		"-2149.429443 -1278.376221 11616.031250"
		"angle"		"-14.569135 77.993065 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"23"
	{
		"origin"		"-1875.831909 -1258.550537 11526.951172"
		"angle"		"-0.752394 68.474510 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"24"
	{
		"origin"		"-1393.484009 -223.726471 11488.031250"
		"angle"		"-0.807125 -33.653717 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"25"
	{
		"origin"		"-1662.394409 435.867798 11519.232422"
		"angle"		"-0.752419 -61.917637 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"26"
	{
		"origin"		"-1949.954346 127.593994 11552.031250"
		"angle"		"1.764684 62.787678 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"27"
	{
		"origin"		"-173.776566 -830.728271 11776.031250"
		"angle"		"7.072466 -135.307983 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"28"
	{
		"origin"		"-64.034737 -331.804230 11776.031250"
		"angle"		"0.984916 109.397423 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"29"
	{
		"origin"		"-379.060455 -1247.789795 11740.345703"
		"angle"		"4.555305 144.258804 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"30"
	{
		"origin"		"-324.567261 -106.838203 11776.031250"
		"angle"		"-1.477430 3.790161 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"31"
	{
		"origin"		"-288.577484 87.535194 11776.031250"
		"angle"		"-0.984928 154.543808 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"2"
	}
	"32"
	{
		"origin"		"-1682.430908 260.546906 11776.031250"
		"angle"		"-0.424043 -15.593267 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"2"
	}
	"33"
	{
		"origin"		"-2422.694824 585.259033 11776.031250"
		"angle"		"89.000000 61.279972 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"34"
	{
		"origin"		"-2322.744141 835.368652 11772.148438"
		"angle"		"87.911011 -141.652725 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"35"
	{
		"origin"		"-2439.504639 916.449158 11772.031250"
		"angle"		"55.703075 -33.775280 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"2"
	}
	"36"
	{
		"origin"		"-2188.124756 899.406982 11772.031250"
		"angle"		"88.537933 -80.206238 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"1"
	}
	"37"
	{
		"origin"		"-933.802124 141.212387 11776.031250"
		"angle"		"73.374863 150.670837 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"1"
	}
	"38"
	{
		"origin"		"-449.667511 -651.884460 11771.545898"
		"angle"		"69.783691 -118.458527 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"39"
	{
		"origin"		"-205.214920 -510.191559 11776.031250"
		"angle"		"24.484789 -156.474106 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"40"
	{
		"origin"		"-291.364563 -675.057739 11776.031250"
		"angle"		"16.135843 -127.664940 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"2"
	}
	"41"
	{
		"origin"		"-235.245590 -604.802612 11771.031250"
		"angle"		"88.075867 -83.049103 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"1"
	}
}

**Comment by Fohdeesha** [comment]
here are fixed spawns, once the pull request is accepted they'll be in the official repo https://github.com/splewis/csgo-retakes/pull/207
