### ISSUE TITLE
having too many rounds in a game 

### ISSUE THREAD

**Issue by GTAmama16** [splewis/csgo-retakes#208]
having both latest version for SM and plugin 

already set mp_maxrounds 30 in gamemode, server and retake-game.cfg 

but game still going over 30 rounds and used to go to 50~60 rounds in a game 
any solution ?

**Comment by shmidtelson** [comment]
Send please 
server.cfg
gamemode_..._server.cfg
reteake-game.cfg

**Comment by GTAmama16** [comment]
found the issue, its the insta-defuse plugin
