### ISSUE TITLE
Fixed Spawn Vertigo After Release Notes for 10/9/2019 Update

### ISSUE THREAD

**Issue by rpkaul** [splewis/csgo-retakes#214]
"Spawns"
{
	"0"
	{
		"origin"		"-205.611542 -680.189270 11774.031250"
		"angle"		"3.630006 -100.134407 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"1"
	}
	"1"
	{
		"origin"		"-31.031250 -881.076538 11776.031250"
		"angle"		"0.857996 -136.929260 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"2"
	{
		"origin"		"-56.483925 -1198.080688 11776.031250"
		"angle"		"0.560904 127.403717 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"3"
	{
		"origin"		"-375.736237 -1475.031982 11776.031250"
		"angle"		"0.395899 120.869438 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"4"
	{
		"origin"		"-958.061096 -1473.409790 11776.031250"
		"angle"		"0.395900 105.227364 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"5"
	{
		"origin"		"-407.578644 -1270.770752 11730.828125"
		"angle"		"-6.336264 82.028275 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"6"
	{
		"origin"		"-1085.700562 -672.004211 11776.031250"
		"angle"		"0.461735 14.771087 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"7"
	{
		"origin"		"-1165.968750 -829.245483 11776.031250"
		"angle"		"-0.198281 -68.322929 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"8"
	{
		"origin"		"-87.274704 -465.222870 11904.031250"
		"angle"		"8.579686 -172.704681 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"9"
	{
		"origin"		"-496.460144 -297.358521 11776.031250"
		"angle"		"-1.452398 153.305374 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"10"
	{
		"origin"		"-558.915039 -673.517822 11776.031250"
		"angle"		"-0.693398 51.102020 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"11"
	{
		"origin"		"-1293.958130 -785.528564 11488.031250"
		"angle"		"0.527551 102.153122 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"12"
	{
		"origin"		"-1700.319458 -890.968750 11488.031250"
		"angle"		"-0.297449 61.728088 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"13"
	{
		"origin"		"-1589.536377 -363.303406 11488.031250"
		"angle"		"2.606550 35.625038 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"14"
	{
		"origin"		"-1612.968750 310.232788 11494.519531"
		"angle"		"3.827550 -58.293007 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"15"
	{
		"origin"		"-847.204041 843.925903 11776.031250"
		"angle"		"3.101550 -71.196327 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"16"
	{
		"origin"		"-1250.201904 985.117554 11776.031250"
		"angle"		"0.296551 -71.592621 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"17"
	{
		"origin"		"-940.995178 812.472656 11776.031250"
		"angle"		"0.494551 -100.368629 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"18"
	{
		"origin"		"-1939.353149 -159.388824 11776.031250"
		"angle"		"4.421560 60.801685 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"19"
	{
		"origin"		"-1703.790649 370.861755 11776.031250"
		"angle"		"6.038560 -28.661434 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"20"
	{
		"origin"		"-1411.433350 -364.725250 11776.031250"
		"angle"		"5.741560 130.233780 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"21"
	{
		"origin"		"-2208.243408 869.532288 11774.031250"
		"angle"		"0.230483 -96.345818 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"1"
	}
	"22"
	{
		"origin"		"-2507.328369 1065.618408 11783.228516"
		"angle"		"-1.452603 -0.018488 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"23"
	{
		"origin"		"-2624.034912 960.635498 11785.858398"
		"angle"		"0.494397 -93.738579 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"24"
	{
		"origin"		"-2607.230713 659.666748 11783.793945"
		"angle"		"-4.785602 -30.345528 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"25"
	{
		"origin"		"-2633.968750 362.541565 11787.920898"
		"angle"		"0.593398 -58.824554 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"26"
	{
		"origin"		"-1715.036987 593.429382 11776.031250"
		"angle"		"0.791398 39.812569 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"27"
	{
		"origin"		"-1393.031250 608.019714 11776.031250"
		"angle"		"1.682397 91.754608 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"28"
	{
		"origin"		"-1929.579712 1047.054932 11780.948242"
		"angle"		"3.629397 -47.241310 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"29"
	{
		"origin"		"-1893.993164 775.677856 11776.031250"
		"angle"		"-0.594604 -142.842209 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"30"
	{
		"origin"		"-2151.031250 439.965729 11776.031250"
		"angle"		"2.177390 -96.378395 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"31"
	{
		"origin"		"-1368.476196 -67.802322 11488.031250"
		"angle"		"-1.023631 122.513435 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"32"
	{
		"origin"		"-1456.009155 -435.871216 11488.031250"
		"angle"		"0.362369 95.189293 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"33"
	{
		"origin"		"-2504.033447 -830.113159 11776.031250"
		"angle"		"4.058369 24.107382 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"34"
	{
		"origin"		"-2046.968750 -499.711182 11776.031250"
		"angle"		"1.715369 7.244431 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"35"
	{
		"origin"		"-1531.743408 -663.998779 11776.031250"
		"angle"		"0.197370 82.253471 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"36"
	{
		"origin"		"-1310.031250 -328.573853 11776.031250"
		"angle"		"0.428370 145.514252 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"37"
	{
		"origin"		"-904.158508 -185.570511 11776.031250"
		"angle"		"3.530369 107.236977 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"38"
	{
		"origin"		"-718.570435 382.543030 11776.031250"
		"angle"		"4.190370 105.389084 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"39"
	{
		"origin"		"-793.261292 943.020691 11776.031250"
		"angle"		"2.441370 -154.752823 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"40"
	{
		"origin"		"-943.115356 276.611694 11776.031250"
		"angle"		"3.167370 115.948997 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
}

**Comment by splewis** [comment]
Pull requests welcome.
