### ISSUE TITLE
Spawn for New Cache 

### ISSUE THREAD

**Issue by rpkaul** [splewis/csgo-retakes#215]
"Spawns"
{
	"0"
	{
		"origin"		"170.638123 1938.050171 1687.031250"
		"angle"		"-2.541374 -98.744560 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"1"
	{
		"origin"		"341.579956 1657.342407 1687.031250"
		"angle"		"-2.211375 -156.989288 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"2"
	{
		"origin"		"683.929443 1782.477295 1702.031250"
		"angle"		"-1.089374 -94.718292 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"3"
	{
		"origin"		"654.116699 1175.443726 1702.031250"
		"angle"		"-3.828373 -91.055275 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"4"
	{
		"origin"		"759.890503 1546.283569 1702.031250"
		"angle"		"-1.650374 166.876007 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"5"
	{
		"origin"		"-11.120682 1373.393433 1687.031250"
		"angle"		"5.147625 -170.386993 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"6"
	{
		"origin"		"-61.460266 2174.462646 1687.031250"
		"angle"		"1.715611 -93.665024 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"0"
	}
	"7"
	{
		"origin"		"-1242.000244 92.376656 1613.175659"
		"angle"		"1.682611 36.226238 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"8"
	{
		"origin"		"-838.425293 316.405945 1614.031250"
		"angle"		"-4.719388 92.524178 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"9"
	{
		"origin"		"-413.010559 -8.044181 1665.031250"
		"angle"		"1.517599 101.500275 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"10"
	{
		"origin"		"276.464874 203.434036 1613.031250"
		"angle"		"2.870599 179.314392 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"11"
	{
		"origin"		"513.369690 356.206909 1613.418579"
		"angle"		"2.738599 -176.527313 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"12"
	{
		"origin"		"651.425781 27.498343 1630.588379"
		"angle"		"6.368617 -126.070534 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"13"
	{
		"origin"		"1465.353638 219.151169 1613.031250"
		"angle"		"-2.145364 78.337769 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"14"
	{
		"origin"		"1538.170776 734.613403 1613.000122"
		"angle"		"-3.267364 175.852890 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"15"
	{
		"origin"		"1251.275269 1068.337158 1654.103516"
		"angle"		"-3.663364 99.226791 0.000000"
		"bombsite"		"A"
		"team"		"CT"
		"type"		"0"
	}
	"16"
	{
		"origin"		"1336.059692 113.581444 1613.031250"
		"angle"		"2.474636 -126.166298 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"17"
	{
		"origin"		"959.962708 319.408722 1613.031250"
		"angle"		"4.883636 -154.249130 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"18"
	{
		"origin"		"483.292206 374.690582 1613.520508"
		"angle"		"-1.485363 -88.546059 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"19"
	{
		"origin"		"-167.464798 338.138245 1613.031372"
		"angle"		"-0.462363 -44.161095 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"20"
	{
		"origin"		"-967.484619 844.727234 1660.725220"
		"angle"		"1.319637 -83.860329 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"21"
	{
		"origin"		"-1326.671387 378.798828 1612.983887"
		"angle"		"-4.686362 -48.088131 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"22"
	{
		"origin"		"2058.946045 -869.222656 1613.031128"
		"angle"		"0.494629 163.478287 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"23"
	{
		"origin"		"2466.153564 -313.684784 1613.031250"
		"angle"		"-3.135370 -135.009857 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"24"
	{
		"origin"		"1223.582275 -270.139099 1612.031250"
		"angle"		"-0.165371 -146.889572 0.000000"
		"bombsite"		"B"
		"team"		"CT"
		"type"		"0"
	}
	"25"
	{
		"origin"		"-6.339733 -1117.221069 1659.031250"
		"angle"		"22.142593 89.327255 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"1"
	}
	"26"
	{
		"origin"		"-73.529427 -1405.904785 1659.031250"
		"angle"		"0.593588 90.020164 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"1"
	}
	"27"
	{
		"origin"		"-370.659973 -1210.031616 1613.031250"
		"angle"		"-0.066421 82.727280 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"28"
	{
		"origin"		"-367.627930 -745.411987 1613.031250"
		"angle"		"0.362580 5.507419 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"29"
	{
		"origin"		"-308.493500 -322.128082 1614.031250"
		"angle"		"0.560587 3.194314 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"30"
	{
		"origin"		"-15.816124 -536.904480 1613.031250"
		"angle"		"0.791587 -29.508698 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"31"
	{
		"origin"		"105.084961 -976.901367 1608.176025"
		"angle"		"1.484608 168.103607 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"32"
	{
		"origin"		"179.966156 -1283.035889 1659.031250"
		"angle"		"1.484623 143.056610 0.000000"
		"bombsite"		"B"
		"team"		"T"
		"type"		"0"
	}
	"33"
	{
		"origin"		"-126.268066 1966.226929 1687.032471"
		"angle"		"7.325615 25.135061 0.000000"
		"bombsite"		"A"
		"team"		"T"
		"type"		"1"
	}
}

**Comment by shmidtelson** [comment]
Thank you!

**Comment by borzaka** [comment]
There is also an updated spawns in the repo which works booth the old and new Cache:
https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_cache.cfg
