### ISSUE TITLE
Balance not working

### ISSUE THREAD

**Issue by xeeek** [splewis/csgo-retakes#219]
For some reason, people can go from speculators to players. And it turns out such a thing as in the screenshot. sm_retakes_maxplayers 9
- Plugin version: 0.3.4
![20191101205624_1](https://user-images.githubusercontent.com/52924403/68041853-ec637a80-fcea-11e9-90b4-37ff64efc11f.jpg)

**Comment by splewis** [comment]
Full steps to reproduce? Ideally possible with fewer players (3?).

**Comment by splewis** [comment]
Actually, same as this issue: https://github.com/splewis/csgo-retakes/issues/204
