### ISSUE TITLE
Enable/disable mod

### ISSUE THREAD

**Issue by gabriel-munteanu** [splewis/csgo-retakes#22]
Can you include a enable/disable option for this mod so we can install it on war servers?

Thanks!

**Comment by splewis** [comment]
I've added the sm_retakes_enabled cvar (https://github.com/splewis/csgo-retakes/commit/b883333f20321ab5ccd0a63ff470b54445958e7f), but it's not fully tested yet.

You can download a build of it from http://ci.splewis.net/job/csgo-retakes/lastSuccessfulBuild/ if you want. (just updating addons/sourcemod/plugins/retakes.smx is sufficient).

You can disable by doing ``sm_retakes_enabled 0`` (e.g. through rcon or setting it with sm_cvar) or setting it to 1 to enable.

**Comment by gabriel-munteanu** [comment]
Thank you! I'll test it and come back with a reply for feedback.

**Comment by gabriel-munteanu** [comment]
Basically the enabled cvar works :D, but I have one exception.
We have 3 war servers that share the same files(one csgo installation folder). Only for one of this servers I want to enable this plugin. In the server.cfg file, specific to one of the servers I wrote:
sm_cvar sm_retakes_enabled 1.
In the log files and console I see that the command is executed but when I check from the console to see the value of the cvar it shows me 0. Any idea why?

**Comment by splewis** [comment]
server.cfg might be executed too early and run before the plugin even initializes (and creates the enabled cvar), or the cvar might be being set in cfg/retakes/retakes.cfg (depending on whether you had that file regenerated or not when you updated the plugin).

**Comment by gabriel-munteanu** [comment]
I solved it by commenting sm_retakes_enabled 1 in cfg/sourcemod/retakes/retakes.cfg. Thanks!
