### ISSUE TITLE
Player stuck on two positions on B site Cache

### ISSUE THREAD

**Issue by hackspider** [splewis/csgo-retakes#223]
### Expected behavior
Terrorist player can move after planting the bomb on Cache B site (delta and mouz plant)

### Actual behavior
Terrorist player cannot move after planting the bomb on Cache B site (delta and mouz plant)

### Steps to reproduce
- Plugin version: v0.3.4
- Sourcemod version: 1.11.0.6471
- Steps to reproduce (please be specific): 
Changelevel to de_cache
Choose T site
Wait until B site plant (mouz plant or delta plant)
Plant bomb
Try to move after bomb plant

**Comment by borzaka** [comment]
Update your spawn files with the ones that are in this repo.

I have now problems with de_cache, just checked.
