### ISSUE TITLE
Valve voting

### ISSUE THREAD

**Issue by northeaster** [splewis/csgo-retakes#226]
The valve voting does not work when the retake plugin is open.

**Comment by borzaka** [comment]
That's nothing to do with retakes plugin. Disable the `nextmap` SourceMod plugin.

What's your commands for 'Valve voting'?

**Comment by northeaster** [comment]
nextmap plugin is closed.

cvars:
```
mp_endmatch_votenextleveltime 10
mp_match_end_restart 0
mp_endmatch_votenextmap 1
mp_match_end_changelevel 1
mp_match_restart_delay 15
```

**Comment by borzaka** [comment]
Try with: `mp_match_end_changelevel 1`

**Comment by splewis** [comment]
The retakes plugin does not interfere with voting at all. You can set whatever cvars you like in cfg/sourcemod/retakes/retakes_game.cfg.
