### ISSUE TITLE
competitive not loading

### ISSUE THREAD

**Issue by SanjaySRocks** [splewis/csgo-retakes#229]
### Expected behavior
Enable competitive mode in game and show players colors.

### Actual behavior
Not showing player colors and also showing small avatar like casual but actually server running compi mode (tested and checked)

I dont know whats actually causing issue.

### Steps to reproduce
- Plugin version: "CS:GO Retakes" (0.3.4) by splewis
- Sourcemod version: 
SourceMod Version: 1.10.0.6458
    SourcePawn Engine: 1.10.0.6458, jit-x86 (build 1.10.0.6458)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Nov 24 2019 21:15:34
    Built from: https://github.com/alliedmodders/sourcemod/commit/def6d0f
    Build ID: 6458:def6d0f
    http://www.sourcemod.net/

- Steps to reproduce (please be specific): install retake

**Comment by borzaka** [comment]
Are you sure that you start your game server with `+game_type 0 +game_mode 1`?

Try to add `sv_competitive_official_5v5 1` to `retakes_game.cfg`

**Comment by SanjaySRocks** [comment]
> Are you sure that you start your game server with `+game_type 0 +game_mode 1`?
> 
> Try to add `sv_competitive_official_5v5 1` to `retakes_game.cfg`

Thanks mate it was 0 
sv_competitive_official_5v5 1`

#Solved
