### ISSUE TITLE
SMG rounds

### ISSUE THREAD

**Issue by chulicoxd** [splewis/csgo-retakes#232]
Hi, how are you? I have a small problem and I would like to get the SMG menu out and have random SMG rounds pistols smg rifles awp / scout, I tried it with several MyWeaponAllocator and I could not get it to work, could you please help me when Have a little time, I send greetings I hope your answer someday.

**Comment by borzaka** [comment]
You have to use a 3rd party plugin for that.
https://github.com/shanapu/MyWeaponAllocator is you best bet. You can configure SMG rounds.

**Comment by splewis** [comment]
As mentioned, you can write external plugins to define what every weapon allocation method you like, but I can't help you with other people's plugins.
