### ISSUE TITLE
[SM]   [0] CS_TerminateRound

### ISSUE THREAD

**Issue by Proodyr** [splewis/csgo-retakes#234]
[SM] Blaming: retakes.smx
 [SM] Call stack trace:
 [SM]   [0] CS_TerminateRound
 [SM]   [1] Line 896, ././scripting/retakes.sp:heckRoundDone
[SM]   [2] Line 311, ././scripting/retakes.sp::OnClientDisconnect
Forcing client reconnect (3)
 World triggered "Round_Start"

I've got trouble with this any idea what i should do? 
### Expected behavior
Working without errors

### Actual behavior
Clients connecting to server and then they cant choose team or spectate, console sending me actuall error (on top of post)

### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.10 - build 6478
- Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
Try with the latest development build: http://ci.splewis.net/job/csgo-retakes/lastSuccessfulBuild/

**Comment by Proodyr** [comment]
> Try with the latest development build: http://ci.splewis.net/job/csgo-retakes/lastSuccessfulBuild/

didn't help :/ same issue

**Comment by borzaka** [comment]
Update SourceMod/Metamod

What other plugins are you using?

Show us your command how do you started the dedicated server.

Give us more info.

**Comment by Proodyr** [comment]
im using LinuxGSM as my server script, problem is that before some update or idk whats happen everything works fine before. error sounds : 
`[SM] Exception reported: Failed to lookup TerminateRound signature.`
[SM] Listing 26 plugins:
  01 "Admin Help" (1.9.0.6282) by AlliedModders LLC
  02 "Fun Votes" (1.9.0.6282) by AlliedModders LLC
  03 "RankMe" (3.0.3.Kento.29.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  04 "Anti-Flood" (1.9.0.6282) by AlliedModders LLC
  05 "Admin File Reader" (1.9.0.6282) by AlliedModders LLC
  06 "Nextmap" (1.9.0.6282) by AlliedModders LLC
  07 "[Retakes] Bomb Autoplant" (1.5.0) by Techno
  08 "Server Redirect: Ask connect in console" (0.2.5) by H3bus
  09 "Basic Chat" (1.9.0.6282) by AlliedModders LLC
  10 "Server Redirect: Ask connect in chat" (0.2.5) by H3bus
  11 "Basic Info Triggers" (1.9.0.6282) by AlliedModders LLC
  12 "Client Preferences" (1.9.0.6282) by AlliedModders LLC
  13 "Basic Votes" (1.9.0.6282) by AlliedModders LLC
  14 "Player Commands" (1.9.0.6282) by AlliedModders LLC
  15 "Reserved Slots" (1.9.0.6282) by AlliedModders LLC
  16 "CS:GO Retakes" (0.3.4+163) by splewis
  17 "Server Redirect" (0.2.6) by H3bus
  18 "Sound Commands" (1.9.0.6282) by AlliedModders LLC
  19 "Admin Menu" (1.9.0.6282) by AlliedModders LLC
  20 "[Scoreboard] Tags" (1.0) by Mansionz
  21 "Fun Commands" (1.9.0.6282) by AlliedModders LLC
  22 "Basic Ban Commands" (1.9.0.6282) by AlliedModders LLC
  23 "Basic Commands" (1.9.0.6282) by AlliedModders LLC
  24 "CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.2.0) by BatMen
  25 "Basic Comm Control" (1.9.0.6282) by AlliedModders LLC
  26 "Server Redirect: Ask connect with connect box" (0.2.5) by H3bus

**Comment by borzaka** [comment]
SourceMod 1.9 is obsolete and unsupported, and not getting gamedata updates. Which is causing your problem.

You could:
- update gamedata manually based on the newer version of SourceMod
- update to latest SourceMod 1.10

**Comment by splewis** [comment]
This is almost certainly a sourcemod installation issue, not necessarily one of retakes.
