### ISSUE TITLE
AUG and SG not available in weapons menu.

### ISSUE THREAD

**Issue by Enzyoo** [splewis/csgo-retakes#235]
As per the title.

Selections are M4A4, M4A1-S for CT and AK-47 for T.

**Comment by borzaka** [comment]
You can
- use any other weapon allocator (found them AlliedMods forums)
- use the latest version in this repo, not from the releases menu

**Comment by Keetahi** [comment]
I have same problem, and i'm using new retakes_standardallocator.sp, am I missing something here?

**Comment by Enzyoo** [comment]
> I have same problem, and i'm using new retakes_standardallocator.sp, am I missing something here?

I switched to an alternate allocator with more of a diversity in rounds and has more weapons to select.
https://github.com/shanapu/MyWeaponAllocator
