### ISSUE TITLE
No nades

### ISSUE THREAD

**Issue by Dodo7773** [splewis/csgo-retakes#236]
Hi. There are no nades, I've got cvar commands in serwer.cfg to enable nades and .smx file that should give them. Dont know what to do, anyone got this problem?

**Comment by splewis** [comment]
Retakes doesn't give grenades out by itself. 

>I've got cvar commands in serwer.cfg to enable nades and .smx file that should give them

- what commands?
- what plugin are you talking about?

**Comment by Dodo7773** [comment]
These:

sm_retakes_weapon_primary_enabled
sm_retakes_weapon_nades_enabled
sm_retakes_weapon_allow_nades_on_pistol_rounds
sm_retakes_weapon_nades_hegrenade_ct_max 1
sm_retakes_weapon_nades_hegrenade_t_max 1
sm_retakes_weapon_nades_flashbang_ct_max 2
sm_retakes_weapon_nades_flashbang_t_max 2
sm_retakes_weapon_nades_smokegrenade_ct_max 1
sm_retakes_weapon_nades_smokegrenade_t_max 1
sm_retakes_weapon_nades_molotov_ct_max 1
sm_retakes_weapon_nades_molotov_t_max 0

and 
retakes_standardallocator in addons/sourcemod/plugins

**Comment by Dodo7773** [comment]
Ok, I did now notice that there are nades but they are on the ground and nobody can pick them :/
