### ISSUE TITLE
Phrase text fail

### ISSUE THREAD

**Issue by Tarek8220** [splewis/csgo-retakes#237]
![Unavngivet](https://user-images.githubusercontent.com/62396010/77254155-9ffbe580-6c5f-11ea-8fd3-a580478d9bf4.png)

Why does it give me this phrase text everytime bomb is plantet or new round start, i have the txt phrase under translations but still i cant find out why it does that ?

**Comment by borzaka** [comment]
You have to use this plugin, because Valve removed HTML support in hint messages:
https://github.com/Franc1sco/FixHintColorMessages

**Comment by Tarek8220** [comment]
Yeah okay it works now thanks borzaka for the help bro :P
