### ISSUE TITLE
Nuke spawnpoint stuck

### ISSUE THREAD

**Issue by Ziipen** [splewis/csgo-retakes#240]
If reporting a bug, fill in the following sections:

### Expected behavior
Be placed as T not stuck.

### Actual behavior
Being stuck while spawning as T in A

### Steps to reproduce
- Plugin version: Newest
- Sourcemod version: Newest
- Steps to reproduce (please be specific): Play in Nuke.

**Comment by borzaka** [comment]
Which one is the newest? Please specify.
When and where did you download your version?

**Comment by Brodyzera** [comment]
I am having the same issue. Version v0.3.4, downloaded earlier today from the releases page.

**Comment by borzaka** [comment]
Use the [latest development build](http://ci.splewis.net/job/csgo-retakes/lastSuccessfulBuild/) linked in the readme. That contains updated spawns, which has no known bad spawns.

**Comment by splewis** [comment]
As said, you can configure your own spawns. If you know of a specific bad spawn at the latest config, you can let me know, but otherwise you might just have old ones.
