### ISSUE TITLE
Typing in !guns doesnt give the gun menu

### ISSUE THREAD

**Issue by nroomy** [splewis/csgo-retakes#242]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Show a menu where user can select guns

### Actual behavior
Nothign happens. sm_guns doesnt do anything either.

### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.10 build 6482
- Steps to reproduce (please be specific):

Loaded the retakes.smx plugin, executed retakes.cfg. Retakes work, but typing in !guns does nothing. Unloaded all plugins, load only retakes, still nothing. Loaded retakes plugin along with all admin plugins, and still no changes.

**Comment by borzaka** [comment]
You need the `retakes_standardallocator.smx` plugin to be able to change guns, which is disabled by default. You have to move it from the _disabled_ folder where the retakes.smx file is.

**Comment by splewis** [comment]
Yes, retakes does not have a `!guns` command by default. You need another plugin to decide what the menu will actually create it and control what it does.
