### ISSUE TITLE
Question - (also de_cbble coordinates is outdated)

### ISSUE THREAD

**Issue by AleCTC** [splewis/csgo-retakes#245]
Hello,

I'm trying to add my own coordinates to some maps, and wonder what 'type' covers under addons\sourcemod\configs\retakes\. I see some being type 0, and others type 2.

After testing a couple of times, i can see that de_cbble uses some coordinates from before the huge update. You spawn out in nowhere now. Some on A (2 or 3 spawnpoints), and B (1 or 2).
I took a screenshot of 2 of the spawns: https://imgur.com/a/KuHcCQ3

**Comment by splewis** [comment]
They map to these values: https://github.com/splewis/csgo-retakes/blob/b43b47772ea71e0a41833a981a2362f1d67a108b/scripting/include/retakes.inc#L11-L17

The in-game editor does show more user friendly names.

**Comment by AleCTC** [comment]
Neat, thanks! Here's an updated de_cbble in return!
Only problem i have is, the bomb is spawned at their heads (in the air) when using an autoplant plugin. Guessing the origin is from eye view?

`// de_cbble (22/04/2020) - Made with "cl_showpos 1" by Koga73.
// Made for 20 slots servers (10 spawns at each bombsite for each team)

// Spawn types. These only apply to T-side spawns, all 
// CT-spawns are considered SpawnType_Normal since they have no bomb. 
// SpawnType SpawnType_Normal = 0, SpawnType_OnlyWithBomb = 1, SpawnType_NeverWithBomb = 2, 

"Spawns"
{
            // [T] Terrorist Bombsite A (10 Spawns) (4 of them bomb plant friendly)
	"0"                                         // Bomb Friendly
	{
		"origin"		"-2350.87 -1072.85 110.09"
		"angle"		    "4.30 83.39 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "1"
	}
	"1"                                         // Bomb Friendly
	{
		"origin"		"-2338.19 -980.69 136.92"
		"angle"		    "2.45 148.62 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "1"
	}
	"2"                                         // Bomb Friendly
	{
		"origin"		"-2340.26 -1340.18 60.86"
		"angle"		    "-9.01 -27.24 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "1"
	}
	"3"
	{
		"origin"		"-2340.26 -1340.18 60.86"
		"angle"		    "-9.01 -27.24 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"4"                                         // Bomb Friendly
	{
		"origin"		"-2333.10 -910.72 64.02"
		"angle"		    "14.95 80.41 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "1"
	}
	"5"
	{
		"origin"		"-2547.99 -614.99 80.93"
		"angle"		    "-0.28 173.52 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"6"
	{
		"origin"		"-2953.21 -1206.74 96.09"
		"angle"		    "2.29 89.41 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"7"
	{
		"origin"		"-2105.58 -1165.49 64.09"
		"angle"		    "3.54 -0.07 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"8"
	{
		"origin"		"-2319.37 -1768.51 36.50"
		"angle"		    "-0.10 56.82 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"9"
	{
		"origin"		"-2367.77 -767.71 54.98"
		"angle"		    "14.73 22.11 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
	"10"
	{
		"origin"		"-2420.37 -363.77 -115.18"
		"angle"		    "8.30 56.46 0.00"
		"bombsite"		"A"
		"team"		    "T"
		"type"		    "2"
	}
            // [CT] Counter-Terrorist Bombsite A (10 Spawns)
	"11"
	{
		"origin"		"-2083.99 645.37 -132.52"
		"angle"		    "7.25 -159.32 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"12"
	{
		"origin"		"-2073.84 1097.76 -73.23"
		"angle"		    "6.68 -131.89 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"13"
	{
		"origin"		"-2821.04 1034.90 64.09"
		"angle"		    "1.26 -83.68 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"14"
	{
		"origin"		"-2720.60 886.98 64.09"
		"angle"		    "0.65 -102.03 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"15"
	{
		"origin"		"-2454.79 1409.52 64.09"
		"angle"		    "8.15 -101.49 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"16"
	{
		"origin"		"-1045.51 -1204.65 -23.91"
		"angle"		    "-3.54 156.19 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"17"
	{
		"origin"		"-626.32 -849.30 -50.84"
		"angle"		    "-7.34 -163.35 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"18"
	{
		"origin"		"-373.58 -795.40 -34.19"
		"angle"		    "0.67 -164.34 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"19"
	{
		"origin"		"-878.42 -415.14 72.09"
		"angle"		    "6.78 -139.45 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
	"20"
	{
		"origin"		"-769.72 -516.01 32.09"
		"angle"		    "-0.16 -168.18 0.00"
		"bombsite"		"A"
		"team"		    "CT"
		"type"		    "0"
	}
            // [T] Terrorist Bombsite B (10 Spawns) (5 of them bomb plant friendly)
	"21"                                         // Bomb Friendly
	{
		"origin"		"193.92 -673.93 -27.91"
		"angle"		    "4.99 -154.65 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "1"
	}
	"22"                                         // Bomb Friendly
	{
		"origin"		"306.73 -947.54 12.42"
		"angle"		    "-1.04 90.44 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "1"
	}
	"23"                                         // Bomb Friendly
	{
		"origin"		"161.58 -1022.04 12.42"
		"angle"		    "5.23 150.99 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "1"
	}
	"24"                                         // Bomb Friendly
	{
		"origin"		"275.96 -1103.31 -7.91"
		"angle"		    "2.26 172.86 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "1"
	}
	"25"                                         // Bomb Friendly
	{
		"origin"		"395.76 -839.65 -7.91"
		"angle"		    "0.53 43.68 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "1"
	}
	"26"
	{
		"origin"		"728.69 -624.49 -32.98"
		"angle"		    "-3.10 104.16 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "2"
	}
	"27"
	{
		"origin"		"133.01 -345.26 0.09"
		"angle"		    "-0.46 -158.37 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "2"
	}
	"28"
	{
		"origin"		"-250.34 -664.58 0.09"
		"angle"		    "-0.12 148.76 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "2"
	}
	"29"
	{
		"origin"		"579.09 -1458.56 -15.91"
		"angle"		    "6.14 121.41 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "2"
	}
	"30"
	{
		"origin"		"-102.83 -1215.26 -45.80"
		"angle"		    "1.20 62.11 0.00"
		"bombsite"		"B"
		"team"		    "T"
		"type"		    "2"
	}
            // [CT] Counter-Terrorist Bombsite B (10 Spawns)
	"31"
	{
		"origin"		"-943.25 312.71 64.09"
		"angle"		    "-6.23 -69.63 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"32"
	{
		"origin"		"-553.57 489.57 63.09"
		"angle"		    "2.20 -100.39 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"33"
	{
		"origin"		"-736.57 288.87 63.09"
		"angle"		    "0.97 -72.41 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"34"
	{
		"origin"		"-983.09 492.79 64.09"
		"angle"		    "1.56 -67.96 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"35"
	{
		"origin"		"-967.12 9.30 192.09"
		"angle"		    "3.86 0.11 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"36"
	{
		"origin"		"-2148.79 -1129.70 66.33"
		"angle"		    "1.46 31.77 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"37"
	{
		"origin"		"-1807.97 -1632.10 160.09"
		"angle"		    "9.95 74.76 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"38"
	{
		"origin"		"-1997.24 -1247.03 64.09"
		"angle"		    "7.59 -43.72 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"39"
	{
		"origin"		"-2276.13 -730.67 34.42"
		"angle"		    "-0.16 -41.49 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
	"40"
	{
		"origin"		"-2251.64 -1274.09 62.63"
		"angle"		    "1.44 41.52 0.00"
		"bombsite"		"B"
		"team"		    "CT"
		"type"		    "0"
	}
}`

**Comment by borzaka** [comment]
de_cbble has already updated spawns in the repo:
https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_cbble.cfg

You must be using an outdated spawn configs, update yours from here:
https://github.com/splewis/csgo-retakes/tree/master/configs/retakes

**Comment by AleCTC** [comment]
> 
> 
> de_cbble has already updated spawns in the repo:
> https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_cbble.cfg
> But feel free to edit this, and make some changes if you wish.
> 
> You must be using an outdated spawn configs, update yours from here:
> https://github.com/splewis/csgo-retakes/tree/master/configs/retakes
> 
> When you edit the spawns with `!edit` chat command, and use the menu on the left, you don't have to worry about variables, it will do for you.
> 
> Try this autoplant plugin: https://github.com/b3none/retakes-autoplant

Thanks!

**Comment by borzaka** [comment]
BTW your spawns are in the air, that's why the bomb is planted in the air with autoplant plugin :)
