### ISSUE TITLE
Remove Revoler in StandardAllocator

### ISSUE THREAD

**Issue by ruinedmoon** [splewis/csgo-retakes#246]
How can i remove R8 Revolver from !guns in StandardAllocator ?

**Comment by splewis** [comment]
There are no pistols in the StandardAllocator plugin: https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_standardallocator.sp

You're probably using a different plugin.

**Comment by borzaka** [comment]
There is a `retakes_pistolallocator` which only includes pistols, but I don't see a revolver there.
Please show us your `sm plugins` list.

**Comment by ruinedmoon** [comment]
I found that i'm using "Customised Weapon Allocator by BatMen". I'll customize it now 🗡️ 
Thank you.
