### ISSUE TITLE
Retakes isn't working (no smx file created)

### ISSUE THREAD

**Issue by inputuserhere** [splewis/csgo-retakes#248]
Sourcemod does indeed work, but retakes isn't working? There isn't any .smx file in plugins and nothing in /disabled for the aforementioned "Addon" plugins.

### Steps to reproduce
- Plugin version: git clone
- Sourcemod version: Sourcemod 1.10.0 Linux
- Steps to reproduce (please be specific):

**Comment by splewis** [comment]
>  There isn't any .smx file in plugins 

You didn't install it then, probably downloaded the wrong files (just the source code maybe?). 

https://github.com/splewis/csgo-retakes#download -> https://github.com/splewis/csgo-retakes/releases/download/v0.3.4/retakes_0.3.4.zip is the download link.

**Comment by inputuserhere** [comment]
Upon further reading, could this have anything to do with gamemodes_server text, along with map groups and gamemodes? Do I possibly need to set it to something specific? I read that CSGO needs this set, I've only ever hosted a CSS server way back.
