### ISSUE TITLE
Version 2.0 kicking for inactivity. 

### ISSUE THREAD

**Issue by ScarletGrey** [splewis/csgo-retakes#25]
It seems the plugin kicks for inactivity very quickly sometimes players who are just joining into the server.

**Comment by splewis** [comment]
The plugin has no logic for kicking players. Something else is kicking them.

**Comment by ScarletGrey** [comment]
hmm thanks.

**Comment by Linnun** [comment]
I had this problem with a fresh Dedicated Server, too. You may want to try "mp_autokick 0" and put it into your startup config, that did the trick for me.
