### ISSUE TITLE
Retakes seems to be broken

### ISSUE THREAD

**Issue by ngx3** [splewis/csgo-retakes#250]
Actual behavior
There are bots even though bot quote is 0. Bots are also playing/spectating and no one can join any teams.
People are trying to join using autoselect and nothing happens. People are trying to join T/CT and can't and its set to the default ratio in the cfg.
At the end of rounds, while at the map voting screen when you choose a map it never goes to the chosen map.

Steps to reproduce
Plugin version: 0.3.4
Sourcemod version: 1.10.0.6484
Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
You have to manage BOTs on your own. That's nothing to do with Retakes plugin.
Unfortunately the `bot_quota` is a somewhat broken command. BOTs will join regardless of the setting, so you have to find another solution. For example you can use this plugin:
https://forums.alliedmods.net/showthread.php?t=237004

And also map choosing feature is nothing to do with Retakes. You have to manage your map cycle on your own. 
Learn the SourceMod Map Management Plugins:
https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)

**Comment by ngx3** [comment]
The map problem is not through Sourcemod, I've verified this.

I'm running game_type  3 (custom) and game_mode 0 and mg_active. Yet when I go to gamemode_custom.cfg and set bot quota to 0 it changes nothing.

**Comment by RavageCS** [comment]
The retakes plugin uses game settings found at cfg/sourcemod/retakes/retakes_game.cfg

So you need to edit your cvars there because it will use values in that file over your gamemode_custom.cfg. If you are using the in game voting you'll need to put the correct settings in that file.

**Comment by ngx3** [comment]
> The retakes plugin uses game settings found at cfg/sourcemod/retakes/retakes_game.cfg
> 
> So you need to edit your cvars there because it will use values in that file over your gamemode_custom.cfg. If you are using the in game voting you'll need to put the correct settings in that file.

That's just it I can't find the game map voting system, it's not in my gamemode_custom.cfg. Should I just remove all the cvars from the gamemode_custom.cfg?

As for the retakes_game.cfg and gamemode_custom.cfg, bot quota is set to 0 and bots join occasionally when map changes.

**Comment by RavageCS** [comment]
Put your custom cvaras in retakes_game.cfg where it says 
// Things you can change, and may want to:

This is where you need to put the cvars to enable voting and changing level if you are not using a sourcemod plugin to vote and change maps.

For the bots joining use the program linked above 
<details>
  <summary>Bot Quota fix</summary>

  ```
  #pragma semicolon 1
#include <sourcemod>

public Plugin:myinfo = 
{
    name = "[CS:GO] Bot Quota fix",
    author = "TheWho",
    description = "Bot Quota fix",
    version = "FINAL",
    url = "http://forums.alliedmods.net/"
}

new Handle:g_hBotQuota;
 
public OnPluginStart()
{
    g_hBotQuota = FindConVar("bot_quota");
    if (g_hBotQuota != INVALID_HANDLE)
    {
        HookConVarChange(g_hBotQuota, OnBotQuotaChange);
    }
}
 
public OnBotQuotaChange(Handle:cvar, const String:oldVal[], const String:newVal[])
{
    if (StringToInt(newVal) > 0)
    {
        SetConVarInt(cvar, 0);
        //return Plugin_Handled;
    }
} 
  ```
</details>

**Comment by borzaka** [comment]
@ngx3 I already told you, that `bot_quota 0` command is broken, you have to use a third party plugin to fix that. I linked a good one.

Trust me, when I say that your map voting is not working because SourceMod takes over. You probably have `nextmap` plugin enabled. Please learn how to use SourceMod default map related plugins. I linked the documentation.

Please pay attention when we try to help you in basic stuff, which is not even related to Retakes.

**Comment by ngx3** [comment]
I thought the bot issue had been fixed, my mistake.

As for the Sourcemod issue, it's not an issue of nextmap because on my other server this end of round voting does not even appear so I assume it has to be because of the retakes plugin. I found many issues with retakes, another being setting "mp_maxrounds" to 16 in the retakes_game.cfg and still changes maps after 5 rounds.

At the end of round a map voting screen pops up (**which has nothing to do with Sourcemod**) and I cannot disable it.

**Comment by borzaka** [comment]
It looks like you have other issues, which are still not related to retakes.
What voting screen? Screenshot plz.

And show us your enabled plugins list. If you want anybody to help you, provide as many information as possible.

**Comment by ngx3** [comment]
@borzaka 
![endofroundvoting](https://user-images.githubusercontent.com/16364958/82008575-17843a80-963b-11ea-9d05-b66cd7645304.jpg)

**Comment by borzaka** [comment]
That's the native CS:GO voting system. You have to configure your server right to use it.
It's out of scope of the Retakes plugin.

**Comment by splewis** [comment]
I don't see anything that looks like a retakes issue left here, so I'll go ahead and close this.
