### ISSUE TITLE
Start round HUD

### ISSUE THREAD

**Issue by EdwinHD** [splewis/csgo-retakes#252]
Actual behavior
![image](https://user-images.githubusercontent.com/65464824/82128113-3f050f80-97c1-11ea-85d2-a75b22978943.png)
How can i repair this. 
This happens at start rounds
### Steps to reproduce
- Plugin version: 0.3.4
- Sourcemod version: 1.10
- Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
That's another plugin, probably this one:
https://github.com/shanapu/MyWeaponAllocator

Ask help there. It's nothing to do with retakes.

But this is your lucky day, I help you. Use this plugin:
https://github.com/Franc1sco/FixHintColorMessages
But don't complain about the `$`. ;)

**Comment by EdwinHD** [comment]
Thanks :D
