### ISSUE TITLE
retake server issue

### ISSUE THREAD

**Issue by ujbaloch** [splewis/csgo-retakes#253]
when im installing retake server in my other server it keep making player respawning again and again 

im copying same retake folder which is installed in my 1st server

can u please tell me what wrong im doing ?

**Comment by borzaka** [comment]
Need more info, without it we can only guessing...

- Have you followed the installation procedure? https://github.com/splewis/csgo-retakes#requirements
- Have you installed SourceMod?

Show us your `sm plugins list` console output.
