### ISSUE TITLE
retake spawn glitch

### ISSUE THREAD

**Issue by TheTacoMansCode** [splewis/csgo-retakes#257]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
plant on a site on nuke, easy

### Actual behavior
get stuck in wall and cant get out 

this is on nuke , you get stuck in the wall and cant get out, on a site by the silo , just need to change the spawn location

### Steps to reproduce
- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by borzaka** [comment]
Use the latest version, which has no bad spawns:
https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_nuke.cfg
