### ISSUE TITLE
enable retake on 2 servers with 10

### ISSUE THREAD

**Issue by furzich2015** [splewis/csgo-retakes#264]
Hi guys. I have a question.
I have 10 local server. How can I make the retake plugin work only on 2 out of 10 servers? And is there anyway such an opportunity?

**Comment by borzaka** [comment]
Use different users, or different install spaces.

Not really related to retakes.

**Comment by splewis** [comment]
Not very easily: https://wiki.alliedmods.net/Multiple_or_Forked_Servers_(SourceMod)#:~:text=SourceMod%20does%20not%20support%20running,to%20the%20same%20SourceMod%20install. Not specific to retakes, though.

**Comment by furzich2015** [comment]
EDIT Not supported anymore since 02.09.2019 CS:GO update (SM Build 6282) :(
