### ISSUE TITLE
i need cfg cbble classic

### ISSUE THREAD

**Issue by chulicoxd** [splewis/csgo-retakes#278]
I need a retake cfg for the de_cbble_classic map for my server for respawn please

**Comment by borzaka** [comment]
Try this:
https://raw.githubusercontent.com/splewis/csgo-retakes/4e0bd5f01f86bcaa14e3f3cde26629e01fd14ba9/configs/retakes/de_cbble.cfg

This is the previous version before the new cbble big changes.
That spawn config is from Apr 6, 2016

**Comment by chulicoxd** [comment]
Well thank you very much for answering and helping me
