### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by ruslumberjack** [splewis/csgo-retakes#281]
How do I disable bots so they don't go into spectator and break the game?

**Comment by borzaka** [comment]
You use a plugin for that. For example: https://forums.alliedmods.net/showthread.php?t=237004

**Comment by splewis** [comment]
The default configs for retakes sets `bot_quota 0`, so shouldn't need to do anything generally: https://github.com/splewis/csgo-retakes/blob/2c24fa66c67e628ebd720cd15580f8f99755690d/cfg/sourcemod/retakes/retakes_game.cfg#L3

You can always add other plugins / configs to remove bots if you want, though.
