### ISSUE TITLE
Can't switch weapons randomly

### ISSUE THREAD

**Issue by minim0vz** [splewis/csgo-retakes#285]
### Expected behavior
Able to switch between knife and primary weapon as normal

### Actual behavior
Randomly i can't switch to my primary or secondary weapon, only to knife and grenades, being unable to take fights unless i throw a grenade to force the client to pull the primary weapon

- Plugin version:
CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.2.0) by BatMen
[Retakes] Instant Defuse (1.4.0) by B3none
CS:GO Retakes (0.3.4) by splewis
- Sourcemod version: SourceMod Version: 1.10.0.6492
- Steps to reproduce (please be specific):Still unknown, as far as i can tell its random but i noticed it's more common during the first few mins after map change

> plugins running: 
> 01 "Log Connections" (1.1) by Xander (Player 1)
>   02 "CS:GO Retakes: Customised Weapon Allocator for splewis retakes plugin" (0.2.0) by BatMen
>   03 "Admin Help" (1.10.0.6491) by AlliedModders LLC
>   04 "[Retakes] Instant Defuse" (1.4.0) by B3none
>   05 "Basic Ban Commands" (1.10.0.6491) by AlliedModders LLC
>   06 "Sound Commands" (1.10.0.6491) by AlliedModders LLC
>   07 "TOG Clan Tags" (2.2.9) by That One Guy
>   08 "Admin Menu" (1.10.0.6491) by AlliedModders LLC
>   09 "Fix Hint Color Messages" (1.2.2 Franc1sco franug github version) by Phoenix (˙·٠●Феникс●٠·˙)
>   10 "Discord: CallAdmin" (1.1) by .#Zipcore
>   11 "Basic Commands" (1.10.0.6491) by AlliedModders LLC
>   12 "Molotov Friendly Fire" (1.0) by Ilusion9
>   13 "AFK Manager" (4.3.0) by Rothgar
>   14 "Custom Messages" (1.2b) by [Nick_6893 mod by YoNer and minim0vz
>   15 "Cronjobs" (2.0) by dordnung
>   16 "Basic Votes" (1.10.0.6491) by AlliedModders LLC
>   17 "Move Commands ( ResetScore, Switch, Spec )" (2.0.1) by Bara
>   18 "Basic Info Triggers" (1.10.0.6491) by AlliedModders LLC
>   19 "Chat-Processor" (2.2.3) by Drixevel
>   20 "CS:GO Retakes" (0.3.4) by splewis
>   21 "CallAdmin" (0.1.8) by Impact, dordnung
>   22 "Admin File Reader" (1.10.0.6491) by AlliedModders LLC
>   23 "Map Decals" (1.2) by Berni, Stingbyte
>   24 "Weapons & Knives" (1.7.0) by kgns | oyunhost.net
>   25 "Discord API" (1.0) by .#Zipcore, Credits: Shavit, bara, ImACow and Phire
>   26 "Nextmap" (1.10.0.6491) by AlliedModders LLC
>   27 "ServerAdvertisements3" (3.1.4) by ESK0
>   28 "Basic Chat" (1.10.0.6491) by AlliedModders LLC
>   29 "In-game Help Menu" (0.3) by chundo
>   30 "Client Preferences" (1.10.0.6491) by AlliedModders LLC
>   31 "Fun Commands" (1.10.0.6491) by AlliedModders LLC
>   32 "Fun Votes" (1.10.0.6491) by AlliedModders LLC
>   33 "Gloves" (1.0.4) by kgns | oyunhost.net
>   34 "Reserved Slots" (1.10.0.6491) by AlliedModders LLC
>   35 "Basic Comm Control" (1.10.0.6491) by AlliedModders LLC
>   36 "Anti-Flood" (1.10.0.6491) by AlliedModders LLC
>   37 "Player Commands" (1.10.0.6491) by AlliedModders LLC
>

**Comment by borzaka** [comment]
Probably it's one of your plugins. My guess would be this:
24 "Weapons & Knives" (1.7.0) by kgns | oyunhost.net

**Comment by splewis** [comment]
> 24 "Weapons & Knives" (1.7.0) by kgns | oyunhost.net

Yeah, I can't offer any help when using such plugins. They frequently cause unfixable, erratic behavior on servers, not to mention being banned by Valve's TOS.
