### ISSUE TITLE
Error after CSGO update( Release Notes for 12/3/2020) 

### ISSUE THREAD

**Issue by rpkaul** [splewis/csgo-retakes#286]
L 12/04/2020 - 05:38:18: [SM] Exception reported: Failed to lookup TerminateRound signature.
L 12/04/2020 - 05:38:18: [SM] Blaming: retakes.smx
L 12/04/2020 - 05:38:18: [SM] Call stack trace:
L 12/04/2020 - 05:38:18: [SM]   [0] CS_TerminateRound
L 12/04/2020 - 05:38:18: [SM]   [1] Line 893, C:\Users\PC\Desktop\compiler\scripting\retakes.sp::CheckRoundDone
L 12/04/2020 - 05:38:18: [SM]   [2] Line 308, C:\Users\PC\Desktop\compiler\scripting\retakes.sp::OnClientDisconnect
L 12/04/2020 - 05:38:18: Error log file session closed.
  

Also we are getting 1v1 arena gamemode in warmup 
pic - https://ibb.co/MRyDcRV

**Comment by borzaka** [comment]
Wait for the SourceMod guys to update.
There will be a new gamedata update, or even a new release:
https://www.sourcemod.net/downloads.php?branch=stable
