### ISSUE TITLE
Can we have the dedicated scramble plugin?

### ISSUE THREAD

**Issue by Jusp3** [splewis/csgo-retakes#287]
Any ideas?

**Comment by splewis** [comment]
I'm not sure what you're asking for here.

**Comment by Jusp3** [comment]
The retake plugin includes team scrambling so i would like to have plugin that has only the team scramble. You understand?

**Comment by Lehmustus** [comment]
I am looking something similar like this. I am trying to make retakes server using Valve's new gamemode but there is not team scramble like your's retake plugin. :)

**Comment by Jusp3** [comment]
> I'm not sure what you're asking for here.

**Comment by splewis** [comment]
I'm not planning to add a standalone plugin for this. 

Someone is free to extract the releveant code from this plugin, of course, though I don't know if there's any special changes to work with the Valve gamemode (it would likely require testing to find out).
