### ISSUE TITLE
No grenades on retakes

### ISSUE THREAD

**Issue by leeord** [splewis/csgo-retakes#289]
Hello guys. I would like to know which command I should use to buy the grenades. In my retake they only have weapons, without grenades. I already had myweaponallocator. but the grenades don't come.

**Comment by leeord** [comment]
// This file was auto-generated by AutoExecConfig read and append beta
// ConVars for plugin "MyWeaponAllocator.smx"


// 0 - disabled, 1 - enable plugin
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_enable "1"

// 0 - chance / 1- rounds
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_rounds_chance "0"

// percent chance a round will be a pistol round (mywa_rounds_chance 0)
// -
// Default: "20"
// Minimum: "0.000000"
mywa_chance_pistol "20"

// percent chance a round will be a force round (mywa_rounds_chance 0)
// -
// Default: "30"
// Minimum: "0.000000"
mywa_chance_force "20"

// percent chance a round will be a deagle round (mywa_rounds_chance 0)
// -
// Default: "5"
// Minimum: "0.000000"
mywa_chance_deagle "5"

// how many round will be pistol round (mywa_rounds_chance 1)
// -
// Default: "3"
// Minimum: "0.000000"
mywa_rounds_pistol "3"

// how many round will be force round (mywa_rounds_chance 1)
// -
// Default: "4"
// Minimum: "0.000000"
mywa_rounds_force "4"

// money for weapons and equipment on fullbuy round
// -
// Default: "16000"
// Minimum: "0.000000"
mywa_money_full "16000"

// money for weapons and equipment on pistol round
// -
// Default: "800"
// Minimum: "0.000000"
mywa_money_pistol "800"

// money for weapons and equipment on forcebuy round
// -
// Default: "2400"
// Minimum: "0.000000"
mywa_money_force "2400"

// min number of player in terrorist team before AWP is available for T
// -
// Default: "3"
// Minimum: "1.000000"
mywa_awp_min_t "3"

// min number of player in terrorist team before scout is available for T
// -
// Default: "2"
// Minimum: "1.000000"
mywa_scout_min_t "2"

// max number of AWPs for terrorist team / 0 - no AWPs
// -
// Default: "1"
// Minimum: "0.000000"
mywa_awp_t "1"

// max number of scouts for terrorist team in force rounds/ 0 - no scouts
// -
// Default: "1"
// Minimum: "0.000000"
mywa_scout_t "1"

// max number of molotovs for terrorist team / 0 - no molotovs
// -
// Default: "2"
// Minimum: "0.000000"
mywa_molotov_t "1"

// max number of smokegrenades for terrorist team / 0 - no smokegrenades
// -
// Default: "2"
// Minimum: "0.000000"
mywa_smoke_t "1"

// max number of flashbangs for terrorist team / 0 - no flashbangs
// -
// Default: "3"
// Minimum: "0.000000"
mywa_flash_t "2"

// max number of HEgrenades for terrorist team / 0 - no HEgrenades
// -
// Default: "3"
// Minimum: "0.000000"
mywa_he_t "1"

// min number of player in counter-terrorist team before AWP is available for CT
// -
// Default: "3"
// Minimum: "1.000000"
mywa_awp_min_ct "3"

// min number of player in counter-terrorist team before scout is available for CT
// -
// Default: "2"
// Minimum: "1.000000"
mywa_scout_min_ct "2"

// max number of AWPs for counter-terrorist team / 0 - no AWPs
// -
// Default: "1"
// Minimum: "0.000000"
mywa_awp_ct "1"

// max number of scouts for counter-terrorist team in force rounds/ 0 - no scouts
// -
// Default: "1"
// Minimum: "0.000000"
mywa_scout_ct "1"

// max number of molotovs for counter-terrorist team / 0 - no molotovs
// -
// Default: "2"
// Minimum: "0.000000"
mywa_molotov_ct "1"

// max number of smokegrenades for counter-terrorist team / 0 - no smokegrenades
// -
// Default: "2"
// Minimum: "0.000000"
mywa_smoke_ct "1"

// max number of flashbangs for counter-terrorist team / 0 - no flashbangs
// -
// Default: "3"
// Minimum: "0.000000"
mywa_flash_ct "2"

// max number of HEgrenades for counter-terrorist team / 0 - no HEgrenades
// -
// Default: "3"
// Minimum: "0.000000"
mywa_he_ct "1"

// order to buy the equipments / 0 - random, 1 - 1st grenades 2nd armor & kit, 2 - 1st armor & kit 2nd grenades 
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
mywa_buy_order "2"

// 0 - disabled, 1 - enable kevlar
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_kevlar "1"

// 0 - disabled, 1 - enable helm
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_helm "1"

// 0 - disabled, 1 - enable defuser
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_defuser "1"

// 0 - disabled, 1 - enable deagle for pistol & fullbuy rounds
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_deagle "1"

// 0 - disabled, 1 - enable revolver for pistol & fullbuy rounds
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_revolver "0"

// 0 - disabled, 1 - enable bombsite notifications
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
mywa_bombsite "1"

**Comment by leeord** [comment]
SourceMod 1.10.0.6502

**Comment by splewis** [comment]
I can't help you with the myweaponallocator plugin. This repo is only the core retakes plugin. You should probably ask at https://github.com/shanapu/MyWeaponAllocator/issues.

**Comment by leeord** [comment]
I have taken off myweaponallocator off, but it still does not work.. pistol rounds works, and rifle rounds aswell..  but no grenades.. does it have something to do with sourcemods version?
