### ISSUE TITLE
Damage Print

### ISSUE THREAD

**Issue by kurodz** [splewis/csgo-retakes#29]
How can i use your Damageprint plugin in retakes mod.
It says need required pugsetup plugin.

**Comment by splewis** [comment]
You can't. It's part of pugsetup, hence its name, pugsetup_damageprint.

I might make a repository of miscellaneous plugins, which would include a generic damage-printing one, in the future, though.

**Comment by splewis** [comment]
You can get a non-pugsetup version of the plugin from this repository now: https://github.com/splewis/sm-misc

The plugin binary would be in here: http://ci.splewis.net/job/sm-misc/lastSuccessfulBuild/
