### ISSUE TITLE
vertigo not working

### ISSUE THREAD

**Issue by christos-18** [splewis/csgo-retakes#291]
The plugin doesn't work on vertigo or can i do anything to make it work

I have all the latest versions and vertigo doesn't work for me.

**Comment by borzaka** [comment]
Try this: #244

**Comment by ksgoescoding** [comment]
Have you tried re-doing the spawn points? Had the same problem with executes on Inferno, and I redid the spawn points.

**Comment by splewis** [comment]
Sorry, there's not enough information in this report to help. Clear steps to reproduce are the only way someone can help.
