### ISSUE TITLE
RETAKES MESSAGE_PREFIX issue

### ISSUE THREAD

**Issue by homerARG** [splewis/csgo-retakes#293]
Trying to change the natives.sp file by editing the message prefix.

#define MESSAGE_PREFIX "[\x0CLuxeLife\x01]"

Expected behavior
Change the prefix from "[\x0CRetakes\x01]" to "[\x0CLuxeLife\x01]" without there being any unintended consequences.

Actual behavior
There is no way it works, I tried changing the plugin version but nothing happens

Steps to reproduce
Plugin version: 0.3.4+178
SourceMod version: 1.11.0.6675
Steps to reproduce (please be specific):
Edit the natives.sp file to a new name and/or color
Save the file
Boot up the server or change map
Join the server 
The prefix remains the same

**Comment by LuxeLife** [comment]
If i try to compile i get this:

// ----------------------------------------

//// natives.sp
//
// natives.sp(30) : error 017: undefined symbol "IsPlayer"
// natives.sp(32) : error 017: undefined symbol "CS_TEAM_T"
// natives.sp(37) : error 017: undefined symbol "IsPlayer"
// natives.sp(39) : error 017: undefined symbol "Queue_Find"
// natives.sp(50) : error 017: undefined symbol "MESSAGE_PREFIX"
// natives.sp(53) : error 017: undefined symbol "Colorize"
// natives.sp(53) : error 092: number of arguments does not match definition
// natives.sp(56) : error 017: undefined symbol "Colorize"
// natives.sp(56) : error 092: number of arguments does not match definition
// natives.sp(68) : error 017: undefined symbol "MESSAGE_PREFIX"
// natives.sp(69) : error 017: undefined symbol "Colorize"
// natives.sp(69) : error 092: number of arguments does not match definition
// natives.sp(76) : error 017: undefined symbol "MESSAGE_PREFIX"
// natives.sp(77) : error 017: undefined symbol "Colorize"
// natives.sp(77) : error 092: number of arguments does not match definition
// natives.sp(84) : error 017: undefined symbol "g_NumT"
// natives.sp(84) : error 130: cannot coerce functions to values
// natives.sp(88) : error 017: undefined symbol "g_NumCT"
// natives.sp(88) : error 130: cannot coerce functions to values
// natives.sp(92) : error 017: undefined symbol "g_NumT"
// natives.sp(92) : error 130: cannot coerce functions to values
// natives.sp(96) : error 017: undefined symbol "g_Bombsite"
// natives.sp(102) : error 017: undefined symbol "g_RoundPoints"
// natives.sp(102) : warning 215: expression has no effect
// natives.sp(102) : error 001: expected token: ";", but found "]"
// natives.sp(102) : error 029: invalid expression, assumed zero
// natives.sp(102) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0,11 sec
// ----------------------------------------

**Comment by borzaka** [comment]
Yes, you need to compile to see the changes. Compile the `retakes.sp`, which is main file for the plugin.

**Comment by splewis** [comment]
Sorry, I don't provide support for people making arbitrary plugin code edits.
