### ISSUE TITLE
de_ancient configs ?

### ISSUE THREAD

**Issue by bedstespil** [splewis/csgo-retakes#294]
Hey.
I am looking for a configuration file for de_ancient
Anyone can help?
Thanks in advance.

**Comment by borzaka** [comment]
You can always make your own, or wait for someone to publish one.

To make your own: type `!edit` in the chat.

**Comment by rpkaul** [comment]
you can try my config #295

**Comment by crashzk** [comment]
https://github.com/splewis/csgo-retakes/pull/296
