### ISSUE TITLE
Retakes mode not activated

### ISSUE THREAD

**Issue by lopustp** [splewis/csgo-retakes#299]
So I have installed the latest csgo-retakes file and I can't get it working.
When I join my server it has 5 minutes warmup session running then after that It starts the normal "competitive with bots"

- I have installed metamod and sourcemod.
- I have reinstalled everything 3 times and I'm pretty sure I have done that correctly.
- I have checked that metamod and sourcemod work correctly by typing "meta version" and "sm version" to console.
- I have checked sourcemod logs for any issues, but nothing

____________________________________________________________________________________________
[Server] INFO sm version
[Server] INFO SourceMod Version Information:
[Server] INFO SourceMod Version: 1.10.0.6503
[Server] INFO SourcePawn Engine: 1.10.0.6503, jit-x86 (build 1.10.0.6503)
[Server] INFO SourcePawn API: v1 = 5, v2 = 12
[Server] INFO Compiled on: Apr 29 2021 01:29:19
[Server] INFO Built from: https://github.com/alliedmodders/sourcemod/commit/bc122af
[Server] INFO Build ID: 6503:bc122af
[Server] INFO http://www.sourcemod.net/
_____________________________________________________________________________________________
[Server] INFO meta version
[Server] INFO Metamod:Source Version Information
[Server] INFO Metamod:Source version 1.11.0-dev+1144
[Server] INFO Plugin interface version: 16:14
[Server] INFO SourceHook version: 5:5
[Server] INFO Loaded As: Valve Server Plugin
[Server] INFO Compiled on: Dec 27 2020 18:18:22
[Server] INFO Built from: https://github.com/alliedmodders/metamod-source/commit/7341116
[Server] INFO Build ID: 1144:7341116
[Server] INFO http://www.metamodsource.net/
________________________________________________________________________________________________

**Comment by borzaka** [comment]
How did you installed the retakes plugin exactly?

Currently the best way is to install the latest development version:
https://ci.splewis.net/job/csgo-retakes/lastSuccessfulBuild/
And copy the ZIP contents to the right places.

This plugin is not only one file.

**Comment by lopustp** [comment]
I will try on your version.
And yeah I have installed the zip and extracted the ZIP contents to right places...
