### ISSUE TITLE
Add decoys

### ISSUE THREAD

**Issue by RavageCS** [splewis/csgo-retakes#30]
Is there any way to add decoys to available grenades?

I tried something like: but did not work

static void SetNades(char nades[NADE_STRING_LENGTH]) {
    int rand = GetRandomInt(0, 4);
    switch(rand) {
        case 0: nades = "";
        case 1: nades = "s";
        case 2: nades = "f";
        case 3: nades = "h";
        case 4: nades = "d";
    }
}

**Comment by splewis** [comment]
I'll add the ability to give them to the base plugin, but not actually give them elsewhere.

**Comment by RavageCS** [comment]
Thanks works as expected
