### ISSUE TITLE
Bomb has been planted hint text working with sm_retakes_enabled 0

### ISSUE THREAD

**Issue by 4NTEDEGUEM0N** [splewis/csgo-retakes#302]
When playing a pug in the same server, the alert hint that shows which bombsite the bomb was planted, is working even when the retakes plugin is disabled by the command sm_retakes_enabled 0.

**Comment by ilyasafr** [comment]
post your **sm plugins list**, that problem is not from this plugin.

**Comment by 4NTEDEGUEM0N** [comment]
plugins: https://prnt.sc/15g6bx1 (I left almost all the default plugins)

If I play retakes mode and then disable it by the command to play a pug, for exemple, when planting the bomb, the alert hint shows the last bombsite that was played in the retake. (https://prnt.sc/15gbz4b)
And when going straight to the pug, after the server restart, the alert shows: "Bomb planted on bombsite - -" (https://prnt.sc/15gcdwr)

**Comment by ilyasafr** [comment]
that problem is related to MyWeaponAllocator plugin, the easy way to fix it set **mywa_bombsite** to **0**

**Comment by splewis** [comment]
Thanks @ilyasafr, sent a PR: https://github.com/shanapu/MyWeaponAllocator/pull/31

**Comment by 4NTEDEGUEM0N** [comment]
Thanks! It worked!
