### ISSUE TITLE
Understand the retakes_standardallocator.sp

### ISSUE THREAD

**Issue by enghausen** [splewis/csgo-retakes#310]
Hi,

I am getting back to some old project regarding customized retake servers and I am getting in to SourcePawn again. I am making a new weapons allocator just to try it out. I was looking in the retakes_standardallocator.sp for some inspiration, but I don't understand this:

https://github.com/splewis/csgo-retakes/blob/1ef2e1c3e43e3f54d165a0e8dc8bab9bd6198dad/scripting/retakes_standardallocator.sp#L143-L154

Line 150: 
Why would you call the _TRifleMenu(client);_ (from the **MenuHandler_CTRifle**) and not just the GiveAwpMenu(client); like you do in the MenuHandler_TRifle?

I dont understand why a TRifleMenu is in the CTRifle Handler?

Cheers!

**Comment by splewis** [comment]
the menus are displayed in sequence after executing the guns command. ct choice, then t choice, then awp choice.

**Comment by enghausen** [comment]
Sorry, I just assumed the menu only was shown for either CT or T! I did not catch you was not doing any player/side detection!

Thank you very much for this great plugin!

Feel free to close this :-)
