### ISSUE TITLE
Reducing the value of mp_freezetime in retakes_game.cfg

### ISSUE THREAD

**Issue by temey** [splewis/csgo-retakes#313]
The value of mp_freezetime in retakes_game.cfg should be reduced from 4 to 2. The value is too high to serve any rational purpose; you cannot buy weapons in retakes, and 4 seconds is a staggering 10% of the full duration of a 40 second retakes match.

Naturally, sensible server owners lower this value on their servers, and I'd say from my experience that most popular retakes servers have this value set to 1 or 2. However, there is a notable amount of servers where this default value hasn't been touched. I've noticed that this is the case especially when an organization owns multiple servers running different game modes and retakes is just one of them. Most likely the server owner doesn't have enough personal experience of retakes to know that mp_freezetime should be lowered from its default value. This leads to the situation where a noticeable amount of people spends an extra (minimum) 5% of each round (compared to the freezetime being 2 seconds) just waiting and staring at their screens. By lowering the default value of mp_freezetime in the cfg file you could save at least some people from wasting their time by server owners who are not educated enough to change the default value in their servers. Thank you for reading.

**Comment by crashzk** [comment]
This value is used to plant c4, exactly 4 seconds to plant c4.

**Comment by splewis** [comment]
> This value is used to plant c4, exactly 4 seconds to plant c4.

Indeed. 

TBH, I had always planned to add autoplant functionality directly into retakes and shorten freezetime, but never got around to it since I felt it played smoothly without it. (And now there's other plugins that add the automatic c4 planting functionality.)

**Comment by temey** [comment]
Thank you for your answers. The default value of mp_freezetime makes perfect sense to me now, considering that autoplant is not included in your retakes plugin. I have to admit that I thought it was, since despite having played on multiple retakes servers I have yet to encounter a retakes server with no autoplant.
