### ISSUE TITLE
Idea: Slaylosers

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-retakes#34]
This is an idea, not an issue. Some players complains about other players "Saving" and run "outside" the map so they dont die. Even as Terrorist sometimes.

So I was wondering if a slaylosers option could be made for this? I tried finding such a plugin in the forums and google but didnt find a working one for CSGO. It would be nice with a build-in feature with a cvar ofc. :)

https://forums.alliedmods.net/showthread.php?t=133756&page=6
Crashing server.

**Comment by splewis** [comment]
Won't be added here.
