### ISSUE TITLE
[bug] Multi bomber

### ISSUE THREAD

**Issue by jffz** [splewis/csgo-retakes#37]
First time i noticed it, 
2 terrorists spawn with the bomb and both can try to plant.

**Comment by splewis** [comment]
Did you remove ``mp_give_player_c4 0`` from cfg/sourcemod/retakes/retakes_game.cfg?

**Comment by jffz** [comment]
Nop, didn't edited it.

**Comment by splewis** [comment]
Does it happen consistently? And can you check the actual value of ``mp_give_player_c4 0`` on the server while its running?

**Comment by jffz** [comment]
mp_give_player_c4 is set to 1 on server, i searched (grep...) in alll cfg files for "mp_give_player_c4", it's only in cfg/sourcemod/retakes/retakes_game.cfg where it's set to 0

**Comment by jffz** [comment]
It's ok, i just swapped cfg location between spawn points and cvars ....

Thanks =)
