### ISSUE TITLE
adding revolver to "guns" of standard allocator?

### ISSUE THREAD

**Issue by GavoTrav** [splewis/csgo-retakes#44]
How would one go about doing this or can it be done in the file?

**Comment by splewis** [comment]
There's no logical place to add it with that plugin right now. The menus given are for choosing getting an awp yes/no or which M4 - there's no good choice for the revolver. Just like the deagle/five-seven/etc. are largely ignored by that plugin, it makes sense for the revolver to be treated the same way.

Really, I'd rather someone make a config-file-customizable allocator plugin :)

**Comment by RavageCS** [comment]
For my version I use a cvar to control what weapons are allowed:

g_h_sm_retakes_weapon_revolver_enabled = CreateConVar("sm_retakes_weapon_revolver_enabled", "1", "Whether the players can choose Revolver");

public void GiveMenu(int client) {
	Handle menu = CreateMenu(MenuHandler_Menu);
	SetMenuTitle(menu, "Title:");
	AddMenuInt(menu, 1, "revolver");
	if (GetConVarInt(g_h_sm_retakes_weapon_revolver_enabled) == 1)
		AddMenuInt(menu, 2, "revolver");

...............
