### ISSUE TITLE
Server Player Slot Swap

### ISSUE THREAD

**Issue by ddalo** [splewis/csgo-retakes#46]
Where is the portion of the code dealing with how you swap players when the server is at full capacity? I do not like the current iteration as I'm always the one screwed with the swap. It feels like you are picking the swap based on an alphabetized list of names.

**Comment by splewis** [comment]
Assuming you're referring to your experience on my servers: the plugin that does that isn't a part of the retakes code here itself, it's just something I use on my servers.

And I can promise it's random. Doing based on something alphabetized would actually be harder to do (client indices or userids would be easier, but it is indeed random).

**Comment by ddalo** [comment]
I can promise you every time it swaps a player out. It is always me. It has
happened over ten times.

**Comment by ddalo** [comment]
Link to the plugin?
