### ISSUE TITLE
More weapons?

### ISSUE THREAD

**Issue by ButlerZer** [splewis/csgo-retakes#49]
I've seen multiple servers with a retake plugin that has more weapons. (http://forum.pbfortress.com/)
I'm curious if they themselves modified the Retakes plugin to have different weapons?
(I'm not a plugin maker nor can I code. I have a basic understanding how CSGO Servers work)

Because in these servers it's possible to have SMG's, Shotguns, Auto-Snipers, All Pistols and even AK's on CT.
I'm fairly curious about this, since I run a server with your plugin. My friends and I have played 100s of hours on the PBfortress servers and with your plugin on my current server.

It gets boring really fast with only M4's and AK's. :/

Thanks for the response in advance! :)

**Comment by HalfEatenPie** [comment]
Either they coded their own retake plugin or they modified splewis's retake plugin.  

If you're specifically asking for where in the code it's modified, probably on this file: https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_standardallocator.sp 

You can modify the code to include the other guns and rifles, however that's the place I would start looking into editing.

**Comment by ButlerZer** [comment]
As I said, I'm not familiar with code. So I have no Idea how to add the guns.
Also the plugin that is used on the PBfortress servers is almost the same, with a few differences: Guns, Chat popups. For the rest everything seems the same as Splewis's plugin.

**Comment by splewis** [comment]
> I'm not familiar with code. So I have no Idea how to add the guns.

Then you're out of luck unless someone decides to write a fully configurable plugin for giving out weapons.

>  with a few differences: Guns, Chat popups

None of that indicates they aren't using exactly this plugin.
