### ISSUE TITLE
Can't figure out how to have a couple of pistol rounds at the beginning of the game, as opposed to the entire game.

### ISSUE THREAD

**Issue by Saitamasensei** [splewis/csgo-retakes#50]
Hey there, 
No matter what i do, the retakes mode is either gun only or pistol only. Most retakes begin with pistol rounds, before moving onto the guns which is why I think i'm missing something. Any help would be greatly appreciated..

**Comment by splewis** [comment]
You'd have to write your own weapons allocator plugin (or find someone else's who did this). 

I'm working on merging the two weapons-allocator plugins that ship with this (the standard one and the pistol one), but don't know when it'll be done.

**Comment by spot88** [comment]
Is this fixed yet? Or do i need to use BatMan's plugin?

**Comment by splewis** [comment]
I have not done this yet, no. There's nothing to "fix" since nothing is broken, though.]

See #62
