### ISSUE TITLE
Fix the shit spawns

### ISSUE THREAD

**Issue by Sack12** [splewis/csgo-retakes#51]
DO IT you wont

**Comment by nksprzak** [comment]
pls fix this sourcemod mod

**Comment by splewis** [comment]
You're right, I won't.

**Comment by Sack12** [comment]
I tired installed and my cat spontaneously combusted

**Comment by GreYzZ** [comment]
@Sack12 
You know if you talk like this and type in the title "Fix the shit spawns" he won't and he shouldn't.
@splewis
