### ISSUE TITLE
how to handle afk players?

### ISSUE THREAD

**Issue by emko** [splewis/csgo-retakes#52]
if i turn on mp_autokick will that also kick people who are in queue spectators? is it possible to setup that if you are afk for x time it moves you to spectator and someone in queue gets your spot?

**Comment by RavageCS** [comment]
https://www.sourcemod.net/plugins.php?cat=0&mod=-1&title=afk&author=&description=&search=1

**Comment by emko** [comment]
sorry thanks found a good plugin that does it all :+1:
