### ISSUE TITLE
Where is retakes.smx?

### ISSUE THREAD

**Issue by Pumbaya** [splewis/csgo-retakes#56]
I can't find it anywhere and I don't know how to initiate the plug in! Can anyone help, I learned everything I know about running a server and using a plug in so I'm fairly lost...

**Comment by splewis** [comment]
https://github.com/splewis/csgo-retakes/releases/tag/v0.3.0

**Comment by Pumbaya** [comment]
Thanks man, both for the help and for your work! I really appreciate it!
