### ISSUE TITLE
Game is currently full with 9 players

### ISSUE THREAD

**Issue by Ellis1297** [splewis/csgo-retakes#57]
When a 10th player is spectating and wants to join the game it says "game is currently full with 9 players" and is a 5v4, any way to change it so it's a 5v5 instead ? 
Thanks

**Comment by splewis** [comment]
https://github.com/splewis/csgo-retakes#configuration

**Comment by Ellis1297** [comment]
So do i add "sm_retakes_maxplayers 10" to the cfg file ?

**Comment by jinnnnnnnn** [comment]
it's already added, default on 9 edit personally to 10

**Comment by Ellis1297** [comment]
I don't have that in my config file ?
I only have the following:
`// How much time player should be banned if he didnt planted twice. -1 - Do nothing, 0 - Kick client
// -
// Default: "0"
// Minimum: "-1.000000"
retakes_didntplant "0"

// How much Pistols Rounds should be. 0 to disable
// -
// Default: "5"
// Minimum: "0.000000"
retakes_pistols "5"

// How much percent to give a awper a strong pistol by his choice. 0 to disable
// -
// Default: "33"
// Minimum: "0.000000"
// Maximum: "100.000000"
retakes_strongchance "33"

// How much row the T's need to win for scramble. 0 to disable
// -
// Default: "7"
// Minimum: "0.000000"
retakes_winrow "7"
`

**Comment by splewis** [comment]
You're not even using this plugin on your server.

**Comment by Ellis1297** [comment]
Yes I am I used all the files from retakes_0.3.0.zip

**Comment by Ellis1297** [comment]
the one you posted a link to on another issue about the smx file

**Comment by Ellis1297** [comment]
I have re-installed everything from the zip on here and the plugin works but it is not generating a retakes.cfg file ? Any way to fix this please

**Comment by jinnnnnnnn** [comment]
Go to your server > CSGO > cfg > sourcemod > retakes and it should be located here

**Comment by Ellis1297** [comment]
It isn't there. The plugin is loaded in game correctly and everything is working fine apart from there not being a cfg file there ?

**Comment by splewis** [comment]
Then check the error logs in addons/sourcemod/logs. The server is probably missing write permissions in the cfg/sourcemod/retakes directory, blocking it from creating that file.
