### ISSUE TITLE
[Suggestion] Pistol rounds

### ISSUE THREAD

**Issue by nemaides** [splewis/csgo-retakes#6]
As far as i can see there's no way enabling pistol rounds, would be nice to have like round 1-3 be pistol rounds or 1-2 pistol 3 smg, to simulate the matchmaking experience.

**Comment by splewis** [comment]
I'm not interested in maintaining some crazy weapon logic. I'll leave that for others - that's why there are forwards and natives [retakes.inc](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc)
