### ISSUE TITLE
NextMap Assistance

### ISSUE THREAD

**Issue by HaWkz091** [splewis/csgo-retakes#60]
Hi Splewis,

This might be really silly, but I can't for the life of me figure out where the vote for nextmap list sits? I thought it was "server\csgo\maplist.txt". But that isn't right.

I might have deleted stuff in the passed which is why I can not locate it now.

Should I be looking at the bin\csgo\addons\sourcemod\configs?

**Comment by splewis** [comment]
It's usually csgo/mapcycle.txt.

You should be asking on the [sourcemod forums](https://forums.alliedmods.net/forumdisplay.php?f=58) as well, since this isn't specific to retakes.
