### ISSUE TITLE
New Nuke Render Issue

### ISSUE THREAD

**Issue by xXRamagucciXx** [splewis/csgo-retakes#61]
I dont know if its all retakes, or just this one, but the new nuke loads player models as giant error boxes. Any possible fix?

**Comment by splewis** [comment]
It's highly unlikely this has anything to do with retakes.

**Comment by yessiub** [comment]
I am getting the same issue only on new Nuke and only running splewis retake plugin.

**Comment by yessiub** [comment]
http://pasteboard.co/1KIIXUWk.png

**Comment by splewis** [comment]
Have you tried to reproduce it without retakes on the server?

**Comment by yessiub** [comment]
It happens for numerous players on connection.

**Comment by splewis** [comment]
Test it without retakes running on  the server to see if it still happens.

**Comment by BrutalCSEjziponken** [comment]
Im pretty sure I saw this problem on a DM server too.

Try validate the CSGO installation.
