### ISSUE TITLE
How to fix autobalancing

### ISSUE THREAD

**Issue by Saitamasensei** [splewis/csgo-retakes#63]
I want to set up my retakes server as 5v5, but if i allow 10 players in the game at once, it's always 6v4...

Is there a way to change this, and if so pls tell me how...

**Comment by splewis** [comment]
Have you changed the team size ratio cvar?

See https://github.com/splewis/csgo-retakes#configuration

**Comment by Saitamasensei** [comment]
so if i change that to 0.5 it will be even all around

**Comment by splewis** [comment]
Yes.
