### ISSUE TITLE
A way to prioritise the waiting queue

### ISSUE THREAD

**Issue by Saitamasensei** [splewis/csgo-retakes#64]
Is there a way to put admins/donators in front of regular players in the waiting queue? Thank you in advance..

**Comment by HalfEatenPie** [comment]
This is not the right place to ask this question as it has nothing to do with the csgo-retake plugin.  

This is built into Sourcemod itself: https://wiki.alliedmods.net/Reserved_Slots_(SourceMod)

**Comment by splewis** [comment]
No, he's asking about retakes' waiting queue, which isn't related to the reserved slots.

There's forwards the plugin provides that would let you do this.

**Comment by HalfEatenPie** [comment]
Ahh fair enough.  My bad on that then, simply misunderstood it as the Server waiting queue.

**Comment by splewis** [comment]
To elaborate, another plugin can use the [Retakes_OnPreRoundEnqueue](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L41) forward to re-order clients in the waiting queue however it wants. I'm not going to build something like this into retakes itself.
