### ISSUE TITLE
Map not changing at end of map?

### ISSUE THREAD

**Issue by Saitamasensei** [splewis/csgo-retakes#65]
Not sure if this has anything to do with your plugin, but at the end of the map nextmap is set and it just restarts the same map... The only way to switch maps is to either rtv or manually change it. 

Thanks in advance

**Comment by HalfEatenPie** [comment]
It's not related to this plugin at all.

Sourcemod comes with a map change plugin enabled by default (I believe nextmap).  Remove that plugin and your maps should change properly instead of restarting on the same map.

**Comment by Saitamasensei** [comment]
I'll give it a try, thanks for the reply
