### ISSUE TITLE
Overpass spawn problem

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [splewis/csgo-retakes#67]
One of the CT spawns at the stair at the bank is to close to the bomb. They can jump on defuse within a few seconds. I know I can fix this myself (didnt have time yet) but I thought it should be fixed in the release too. :)

**Comment by splewis** [comment]
I think I fixed this a few days ago, but didn't get around to pushing it to github yet. Should be better now (https://github.com/splewis/csgo-retakes/commit/a53a1a5a6d1eb9374ecf7f2510ab15d63df67499)
