### ISSUE TITLE
Taser Support

### ISSUE THREAD

**Issue by RavageCS** [splewis/csgo-retakes#70]
Any chance you can add ability to give taser with Retakes_SetPlayerInfo native? 

Should be a boolean.

**Comment by splewis** [comment]
Not a fan of this since
1. it's pretty gimmicky
2. breaks backwards compatbility (granted that's not terrible since it's not officially released) since it requires a new parameter for ``Retakes_GetPlayerInfo``
3. it can be accomplished without using the native

**Comment by RavageCS** [comment]
Yea I agree its pretty gimmicky and not really necessary, I just have it enabled for admins for fun. 

The problem with not having the native support it is you either have to make changes to GiveWeapons in retakes/spawns.sp and recompile retakes.sp (which is what i did) or make your own player spawn hook and then equip from there. I wasnt sure on what hook would come first so I avoided that.

https://github.com/RavageCS/csgo-retakes/commit/3ca0b589710854468d28998c23767cd9cf365b13#diff-b5b6396a56745c332c4359b4cd78d75b

**Comment by splewis** [comment]
A timer/requestframe callback can be used to avoid that. Don't plan on adding it.
