### ISSUE TITLE
"<Failed>

### ISSUE THREAD

**Issue by ambiition** [splewis/csgo-retakes#72]
My server was currently working but my host is dumb so i have to reinstall everything and i had this retakes before but now it just keeps say failed in console :( and it keeps play the same map...
![f9f28b1eec876de136ffb143851fe84f](https://cloud.githubusercontent.com/assets/18623202/14757687/4da9d038-08c4-11e6-8aed-bf9ee80bcd9d.png)

https://gyazo.com/f9f28b1eec876de136ffb143851fe84f

**Comment by splewis** [comment]
I don't see the retakes plugin listed there.

Check your error logs.

**Comment by ambiition** [comment]
retakes.sp?

**Comment by ambiition** [comment]
cause im trying to use batmen beacause it has both !weapon where u can change both pistol & gun

**Comment by splewis** [comment]
That is an addon plugin to retakes. Not a replacement.

Is retakes.smx in addons/sourcemod/plugins? Because it should be.

**Comment by ambiition** [comment]
Nope, i simply just dragged and dropped all of the folders and such, may u please link me to the smx (indepedently)?

**Comment by ambiition** [comment]
I downloaded csgo-retakes-master and the smx is not in there? cause thats the file i dragged and dropped

**Comment by RavageCS** [comment]
You need to either compile it yourself or download from the releases section

https://github.com/splewis/csgo-retakes/releases

**Comment by ambiition** [comment]
Fixed it, but all i have to do is change the maps how do i do that ?

**Comment by splewis** [comment]
Doesn't directly relate to this plugin. You can put mapchange related cvars in cfg/sourcemod/retakes/retakes_game.cfg if you want, though. I use the mapchooser plugin to handle map rotations.

**Comment by ambiition** [comment]
For some reason the match point isnt 15 and the maps keep replaying whats the mapgroup supposed to be...

**Comment by ambiition** [comment]
Or how do i use the mapchooser to pick the maps i want and such

**Comment by splewis** [comment]
How your server picks maps has nothing to do with retakes. A better place to get help would be the sourcemod forums: https://forums.alliedmods.net/forumdisplay.php?f=58

also
https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)
