### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by Daemonicus73** [splewis/csgo-retakes#73]
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

I am trying to get retakes installed on our Multiplay/Clanforge server but they are saying it fails to compile. They emailed me the error message (see below).

[Quote from Email]
Yes, we were using the latest from the github.

We get the following errors when attempting to compile the addon from source. (We must compile it, else it will not work correctly with Clanforge.)
[End Quote]

### Actual behavior

Compiling retakes.sp...
SourcePawn Compiler 1.7.1-dev+5182
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC
retakes.sp(236) : error 017: undefined symbol "PQ_Clear"
retakes.sp(237) : error 017: undefined symbol "PQ_Clear"
retakes.sp(677) : error 017: undefined symbol "PQ_Clear"
retakes.sp(686) : warning 213: tag mismatch
retakes.sp(693) : warning 213: tag mismatch
retakes.sp(820) : error 017: undefined symbol "Queue_EnqueueFront"
4 Errors.

### Steps to reproduce
- Plugin version:
v0.3.2
- Sourcemod version:
N/A

**Comment by splewis** [comment]
Every version should compile fine (as they do the travis ci and my jenkins instance), so you're/clanforge/whoever doing something wrong.

If I had to guess, 1.7.1-dev+5182 is a bit old, so there may be a compiler bug causing issues or they didn't actually get all the updated source files.

**Comment by splewis** [comment]
Closed due to lack of response/update.
