### ISSUE TITLE
I have no clue on how to install retakes.

### ISSUE THREAD

**Issue by dayik** [splewis/csgo-retakes#74]
I did everything correctly, but the .smx file is missing.

http://steamcommunity.com/profiles/76561198236170674/ Here is my steam profile if I'm not reachable.

Could you please help me Lewis ?

I'm not used to programming so the instructions were pretty unclear for me. I installed smlib & the retake, but i had no SMX files whatsoever included with it.

I have latest version of metamod & sourcemod working correctly.

Thanks !

**Comment by splewis** [comment]
If the .smx file is missing, you didn't download the [actual release](https://github.com/splewis/csgo-retakes/releases/tag/v0.3.2) linked in the [instructions](https://github.com/splewis/csgo-retakes#download).

**Comment by splewis** [comment]
Closed due to lack of response/update.
