### ISSUE TITLE
Spawns Not working

### ISSUE THREAD

**Issue by philmoeslim** [splewis/csgo-retakes#76]
Seems like the spawns arnt working it just spawns me in tspawn on inferno and ends round because i didnt plant
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by splewis** [comment]
It would help if you filled in any of the requested information instead of leaving it blank.

Did you install the spawn files? They should be in addons/sourcemod/configs/retakes.

**Comment by philmoeslim** [comment]
I'm a moron man I figured it out. It was more of my server being not set up
properly than anything but I ended up getting it. Thank you so much for
responding
