### ISSUE TITLE
Cache Spawns not working

### ISSUE THREAD

**Issue by Seclyps** [splewis/csgo-retakes#77]
Cache just spawns in black 

### Expected behavior

Spawn in for retake

### Actual behavior
Spawn in under the map

### Steps to reproduce
- Plugin version:
- Sourcemod version:

**Comment by splewis** [comment]
Update your spawn file for cache then, your using an old one.

https://github.com/splewis/csgo-retakes/blob/master/configs/retakes/de_cache.cfg
