### ISSUE TITLE
2 c4's on spawn glitch

### ISSUE THREAD

**Issue by jackarivera** [splewis/csgo-retakes#78]
on version 0.3.2 on bombsite b of dust 2 (only map i've tested on) I spawn with 2 c4's.

**Comment by splewis** [comment]
Can you reproduce this?

**Comment by jackarivera** [comment]
Yes, every time when I have the game mode competitive or Classic it does this, I have to set the game type to custom. But changing the game type to custom, although fixes the 2 c4 glitch, makes it after 1 round the rounds end instantly and it spams them and eventually crashes the game.

**Comment by splewis** [comment]
Can you check the value of the ``mp_give_player_c4`` cvar? 

I've never experienced this bug.

**Comment by jackarivera** [comment]
That fixed it don't know why it was set to 1. Thanks man
