### ISSUE TITLE
Add more weapon options?

### ISSUE THREAD

**Issue by zoidbergwill** [splewis/csgo-retakes#8]
Would you be open to a PR maybe adding galil and famas to weapon options, for AK and M4 options?

**Comment by splewis** [comment]
I'm purposefully leaving the "standard allocator" plugin simple because the way weapons are given out is more of a configuration thing that I think should be left up to whomever is running a server. I don't plan to really add anything else in the way of weapon options.

**Comment by zoidbergwill** [comment]
Thanks for the quick reply. That makes sense.
