### ISSUE TITLE
Pistol AND Standardallocator

### ISSUE THREAD

**Issue by robingroppe** [splewis/csgo-retakes#83]
Hi Splewis,
thank you for this excellent plugin.
I am using it on two servers.

I can see from the chat on these servers that some people, including myself wish to be able to choose a pistol of their choice in addition to the M4/AK.

Maybe this is a good idea for the future.

Thank you.

**Comment by splewis** [comment]
That's the point of https://github.com/splewis/csgo-retakes/issues/62, which I haven't gotten around to doing yet.

**Comment by Ma-ve** [comment]
I just came to the realization that I've had this for the past few months. Took me quite some time to figure out how and why, but I was using this: https://github.com/BatMen/csgo-retakes-splewis-convar-weapon-allocator allocator, which mimics competitive pistol rounds (800$, spread over your choice for a pistol, nades, armor & kit). Might be worth looking into.

**Comment by splewis** [comment]
Closing since it's a duplicate.
