### ISSUE TITLE
CS update [ 18 AUG 2016 ] Issue.

### ISSUE THREAD

**Issue by dracsovd** [splewis/csgo-retakes#84]
After new CS update [ 18 AUG 2016 ], all retake servers are crashing srcds. 

OS : Windows 10 pro.  version 10.0.10586
Plugin version: 3.2.2
SourceMod Version: 1.7.3-dev+5292
SourcePawn Engine: SourcePawn 1.7, jit-x86 (build 1.7.3-dev+5292)
SourcePawn API: v1 = 4, v2 = 6
Compiled on: Jan 25 2016 17:38:11

**Comment by splewis** [comment]
Have you disabled retakes to confirm it is actually a retakes-fixable issue?

As far as I'm aware the crashing issues are far more widespread, and probably only fixable by valve and/or sourcemod itself.

**Comment by BrutalCSEjziponken** [comment]
I have crashes too on my retakes. I cant confirm if its the retake mod or not.

**Comment by Ma-ve** [comment]
It's not retake, don't worry. Valve are aware and are most likely pushing a fix today.

**Comment by splewis** [comment]
I'm closing this since it since highly unrelated to be retakes-related. You can reopen if it turns out to be related.

**Comment by dracsovd** [comment]
oh sorry, noticed it to happen more often on retake servers.
