### ISSUE TITLE
[retakes.smx] Had to resort to fallback spawn on de_dust2, site=0

### ISSUE THREAD

**Issue by qqlessplz** [splewis/csgo-retakes#85]
[retakes.smx] Had to resort to fallback spawn on de_dust2, site=0

getting this on quote a few maps ive edited the spawns?

clearly the wrong way.

any tips to avoid this in future?

**Comment by splewis** [comment]
This error appears when the plugin can't find suitable spawns for the bomb carrier: aka a "normal" or "only with bomb" spawn that is *inside* the bomb site.
