### ISSUE TITLE
Bypass the queue for Admins/VIP.

### ISSUE THREAD

**Issue by Weeeishy** [splewis/csgo-retakes#87]
Hello,

I've requested this feature in AlliedModders, however no one replied to my thread
https://forums.alliedmods.net/showthread.php?t=287606

Few days later, I saw a guy requesting almost the same feature. Arkarr tried to fill the request but it was bugged. You commented about the forwards, but I'm not experienced with SourcePawn. 
https://forums.alliedmods.net/showthread.php?t=288024

So could it be added in the upcoming updates? If you think it's unnecessary then it's totally understandable.

Thanks for your time!

**Comment by RavageCS** [comment]
Ive been wanting to do this for a while, just never got around to doing it. You can read about forwards:
https://wiki.alliedmods.net/Function_Calling_API_(SourceMod_Scripting)

**Comment by Weeeishy** [comment]
Thank you for the link, I should've said that I have no knowledge with SourcePawn. I'll give it my best though and see if I can do something about it. :smiley:

**Comment by splewis** [comment]
Closing this since I don't there's anything to do here.
