### ISSUE TITLE
Retakes.smx is not being loaded by the server

### ISSUE THREAD

**Issue by rafaluta** [splewis/csgo-retakes#88]
- Plugin version:Build #123 (13/10/2016 21:52:21)
- Sourcemod version:1.9.0

I'm having a problem with my server. It don't load the retake.smx at the run. What can I do? I installed properly.
It's not only retakes.smx but all the others aren't loading as well.

**Comment by splewis** [comment]
Can you post any error logs you have? (addons/sourcemod/logs)

The fact that all your plugins don't load makes it unlikely retakes is responsible here.

**Comment by splewis** [comment]
Closed from no response. You can reopen if you have new information.
