### ISSUE TITLE
New Update for CSGO broke the plugin. 11/29/2016

### ISSUE THREAD

**Issue by dracsovd** [splewis/csgo-retakes#92]
As stated on the Title.

- Teams do not switch sides.
- Whenever a new player joins the game, the guns are defaulted back to pistols on the next round.

Found these on the sourcemod error logs :

L 11/29/2016 - 09:51:55: [SM] Exception reported: Failed to locate function
L 11/29/2016 - 09:51:55: [SM] Blaming: retakes.smx
L 11/29/2016 - 09:51:55: [SM] Call stack trace:
L 11/29/2016 - 09:51:55: [SM]   [0] CS_UpdateClientModel
L 11/29/2016 - 09:51:55: [SM]   [1] Line 25, ././scripting/retakes/generic.sp::SwitchPlayerTeam
L 11/29/2016 - 09:51:55: [SM]   [2] Line 139, ././scripting/retakes/spawns.sp::SetupPlayer
L 11/29/2016 - 09:51:55: [SM]   [3] Line 493, ././scripting/retakes.sp::Event_PlayerSpawn

**Comment by rogeraabbccdd** [comment]
Do you update your sourcemod to the latest version?

**Comment by splewis** [comment]
This is because sourcemod had breakage issues: https://forums.alliedmods.net/showthread.php?t=290981

Update to a more recent build of sourcemod and you'll be good to go.

**Comment by dracsovd** [comment]
Thanks for this. @rogeraabbccdd @splewis :)
