### ISSUE TITLE
Plz add these features

### ISSUE THREAD

**Issue by rishabhc43** [splewis/csgo-retakes#96]
Hey splewis!

Thanks for the great plugin and I appreciate ur effort in making it. One of the best plugins in the game.

I just wanted to give some suggestions to add some new features. Can you plz add the support for grenades, flashes, smoke etc. You can give players not more than 2 grenade randomly. This would make the retake more real. Without grenades, this is just sort of an aim battle. 
Another feature i would like to request is giving an AWP to only one player in the team. Here also only those who opt for choosing an AWP would get it. When multiple guys have opted for AWP, it will be given randomly to only one person.
Eagerly waiting to see these new features in the plugin...ThankYou

**Comment by splewis** [comment]
The retakes plugin is meant to be a base plugin, if users wan't specialized logic for what weapons/nades they are given, they are supposed to use the [plugin's API](https://github.com/splewis/csgo-retakes/blob/master/scripting/include/retakes.inc#L185) for applying custom behavior.

I'd like to have a cvar-customizable plugin like this available with retakes as well (#98), but I doubt that gets done anytime soon.

Also, your AWP example doesn't apply to anything shipped with this retakes plugin. There is at most 1 awp given in the [standard allocator example](https://github.com/splewis/csgo-retakes/blob/master/scripting/retakes_standardallocator.sp), and you won't get awps without that. You're probably playing on servers running other plugins, and there's nothing  I can do to change those.

**Comment by splewis** [comment]
Closing since this isn't going to be added to the base retakes plugin.
