### ISSUE TITLE
Feature: ConVar to not switch teams

### ISSUE THREAD

**Issue by iceman20k** [splewis/csgo-retakes#97]
Hi splewis,

thanks for the great mod! We would like to use it for internal team training, but that is impossible because the players get swapped after each round.

Could you include a convar so that team swapping will never happen and teams stay like the players have joined forever?

When using teamspeak with a password protected csgo-retake-mod server this will let us have a team defense and a team attack in teamspeak and we can start to improve each.

Thanks for your reply!

**Comment by RavageCS** [comment]
There is a cvar for this already.

You want:

sm_retakes_auto_set_teams "0"

**Comment by iceman20k** [comment]
Ok thanks for your reply! Will try it.
