### ISSUE TITLE
Retakes broken after 5/12/17 CSGO update

### ISSUE THREAD

**Issue by luckykev** [splewis/csgo-retakes#99]
@splewis 

**Update to latest SM / update game data to fix: https://www.sourcemod.net/downloads.php?branch=stable**

*Expected behavior*

*Functioning normally*

*Actual behavior*

*Team switching is random, spawned with no guns/armor sometimes, not letting people join, ... just not functioning*

*Errors being spammed:*

*L 05/12/2017 - 23:05:00: [SM] Call stack trace:*
*L 05/12/2017 - 23:05:00: [SM]   [0] CS_UpdateClientModel*
*L 05/12/2017 - 23:05:00: [SM]   [1] Line 25, retakes/generic.sp::SwitchPlayerTeam*
*L 05/12/2017 - 23:05:00: [SM]   [2] ...::UpdateTeams*
*L 05/12/2017 - 23:05:00: [SM]   [3] ...::Event_RoundPreStart*
*L 05/12/2017 - 23:05:00: [SM] Exception reported: Failed to locate function*
*L 05/12/2017 - 23:05:00: [SM] Blaming: retakes.smx*

**Comment by dechristopher** [comment]
Can confirm, experiencing this as well.

**Comment by hitlerscow** [comment]
Made an account to confirm I am also having this issue and it appears every other retake is as well.

**Comment by dracsovd** [comment]
Updating to the latest SM version seemed to have fixed it for me.

**Comment by luckykev** [comment]
Updating to SM 5994 / latest game data seems to be the fix.
